### ISSUE TITLE
Upload to Owncloud send to custom URL instead

### ISSUE THREAD

**Issue by andreapx** [mendhak/gpslogger#1003]
Hi,
since...ever, I auto upload the CSV and the GPX to my NextCloud server (using ownCloud).
I've noticed that it hasn't been uploading anything since the 23th of this month. So I've tried to manually upload the last files, but it trows an error saying that it can't reach the URL that I've set in the custom URL section.
I've tried editing and saving the ownCloud settings, but it keeps doing that. If I click on _Test upload_, it stays there saying _Testing ownCloud upload and after a while that box disappear without saying if it succeeded or not.
I've checked and my NextCloud is working without any problem.
The strange, very strange thing is that I see that the last update of the app was a couple of months ago...how is this possible?
Thanks!

**Comment by mendhak** [comment]
Just to be sure could you generate a debug log with the same errors — manual upload results in error, test upload disappears after a while.  


And send it to me, https://gpslogger.app/#troubleshooting

`gpslogger` at mendhak.com `

I did a local test with a NextCloud container and the upload is working just fine so I don't know if there's some special condition that has to be met for this error.  

Do you have both Custom URL and OwnCloud enabled or just OwnCloud?  I would not expect any crossover like that to happen since OwnCloud uses OwnCloud libraries to upload.

**Comment by mendhak** [comment]
From what I can tell in the debug log, the errors you're seeing from the Custom URL are because it's trying to send each line in the CSV to Custom URL, but the domain in the Custom URL is down (the one with port 5055), and for each point it's trying multiple times.  And if you're on the main UI then you're seeing errors returned from each attempt.  

Then the other part is OwnCloud. I'm not seeing any OwnCloud jobs being run.  I can see them queued, but they're not running afterwards. It's possible that there is a large number of Custom URL jobs that have overwhelmed the app and nothing else is being run now? I've never tested such a scenario so my guess would be to let the app just continue running and eventually that queue should clear.  Or to be sure you can go into app settings and completely reset the app and re enter the OwnCloud URL and credentials and try again.

**Comment by andreapx** [comment]
That makes sense!
Thanks a lot, I'll wait some days and then if it persist, I'll clear data and cache.
Thanks!

-------- Original Message --------

**Comment by mendhak** [comment]
I guess it's probably working now so I'll close this
