### ISSUE TITLE
conscryptprovider invalid signature

### ISSUE THREAD

**Issue by exekutive** [mendhak/gpslogger#1017]
I get a lot of these errors

`00:58:48 ERROR ConscryptProviderInstaller.installIfNeeded:64 - com.mendhak.conscryptprovider found, but with an invalid signature. Ignoring.`

Motorola XT1040
Android 5.1

**Comment by mendhak** [comment]
Where did you load GPSLogger from, and Conscrypt Provider from?

**Comment by exekutive** [comment]
both from f-droid

**Comment by exekutive** [comment]
I've deleted conscrypt provider for now to stop the errors, but it was in this list.

![Screenshot_2022-11-07-11-11-29](https://user-images.githubusercontent.com/4755215/200395284-13b08fd1-6c1a-498a-b128-c278e8073ab6.png)

**Comment by mendhak** [comment]
I was able to recreate the problem!  Sadly I was [misled by this page](https://f-droid.org/docs/Release_Channels_and_Signing_Keys/) and I was checking for the signature `05:F2:E6:59:28:08:89:81:B3:17:FC:9A:6D:BF:E0:4B:0F:A1:3B:4E`.  But actually it turns out that a new signing key is created for each application.  It's `9D:E1:4D:DA:20:F0:5A:58:01:BE:23:CC:53:34:14:11:48:76:B7:5E` ouch.  

I'll add a bugfix for this.  If you want an immediate solution you can install it from the conscrypt repo's Github releases section
https://github.com/mendhak/Conscrypt-Provider/releases

**Comment by exekutive** [comment]
is there a absolute way to determine if Conscrypt Provider is needed or not?

**Comment by mendhak** [comment]
In my testing I just wasn't able to figure out if it's absolutely needed. There are ways to guess that it might be needed. 

If the Android device is pre-Android 10 _and_ the website you're connecting to serves TLS 1.3 _and_ when you try to connect with GPSLogger there's an SSL Handshake error or something similar.  

The first part is easy, and just to make sure, the 'Conscrypt Provider' option in General settings is disabled for Android 10+. 

For the server side, I test with 

    openssl s_client -tls1_3 -connect example.com:443

If a certificate is returned, that means it works with TLS 1.3 (but may also work with TLS 1.2)

**Comment by mendhak** [comment]
Your website is TLS 1.2 and 1.3

**Comment by mendhak** [comment]
Oh DUH I need to update F-Droid's cache haha.   Yep it's working.  

![image](https://user-images.githubusercontent.com/746276/203144278-dc23a7f4-2f4e-4d0b-b3fe-1fc12e8133a6.png)
