### ISSUE TITLE
Logging also GPS accuracy

### ISSUE THREAD

**Issue by juhele** [mendhak/gpslogger#102]
hi,
is it possible to add GPS accuracy in logged parameters?

Reason is that while doing a monitoring (no matter if helicopter, car or on foot), there is a variable accuracy of the coordinates determination and so this also influences the measurement results and the output maps. So it would be helpful to know these data to take this into consideration.

thanks

**Comment by bjohas** [comment]
Hi @mendhak ,

the csv accuracy is given in metres, while the GPX is in HDOP. What relation do you assume? My understanding is that they are related through other device errors, so that conversion is not trivial.

Thanks!

**Comment by mendhak** [comment]
No conversions - I'm grabbing it from the NMEA listener, so it's basically as reported by the device hardware.  In other words, it comes down to your phone!

**Comment by bjohas** [comment]
Thanks! I'd forgotten that Android reports has/getAccuracy. Would you consider adding the accuracy value to the GPX format, I guess using <extensions> within track point, i.e. something like

<trkpt ...>
  ...
  <extensions>
    <n:accuracy></n:accuracy>
  </extensions>
</trkpt>

with some namespace "n"? Could be added to the GPX format, or perhaps be a separate format in the app. In my view it would be useful to have one format that contains all data captured from the GPS device, and the GPX format seems to be the most complete.

Rationale: Basically, we'd like to use the app to accurately determine the locations of certain places and roads (in low-income countries), where those locations are submitted by non-technical users. It's thus really helpful to know the accuracy: If we're within a few 10m, that's fine for most places. We'd like to be able to validate the accuracy through the submitted GPX track.

**Comment by mendhak** [comment]
For extensions, I'd need to move the logging to GPX 1.1 - however 1.1 does not allow for course or speed.  That would mean three things have to be moved to extensions, so in turn it is more harmful.  KML also doesn't provide accuracy.  

For this reason I suggest - have a look at just using HDOP as an [indicator of quality](https://en.wikipedia.org/wiki/Dilution_of_precision_\(GPS\)#Meaning_of_DOP_Values) rather than an exact accuracy value itself.  Or if exact value is needed, use CSV instead.  GPX and KML just won't do it.

I get some of the reasoning behind it, when a device gives a location with "10m accuracy" it doesn't actually mean a circle of 10m radius around that position, unfortunately what maps show us is a guide.  The accuracy actually means something like "If I were to obtain 100 location fixes here, 50 of those would fall within this circle of 10m radius"

**Comment by bjohas** [comment]
Ok, that makes sense. Would it be possible to add more to the text file, to make that comprehensive? I.e. add HDOP, VDOP, PDOP and geoid height to the CSV file?

**Comment by mendhak** [comment]
Yeah I think that should be doable.  Can you create a new issue for this.  When I find some time I can have a look at adding this in.

**Comment by bjohas** [comment]
Thanks! New issue here https://github.com/mendhak/gpslogger/issues/449
