### ISSUE TITLE
Nextcloud behind Cloudflare, GPSlogger doesn't upload

### ISSUE THREAD

**Issue by andreapx** [mendhak/gpslogger#1052]
Hi,
from the moment that I've put Nextcloud server behind Cloudflare, GPSlogger doesn't upload the files, automatically nor manually (fail with status code 403 (fail)).
I've checked Cloudflare logs and it's blocked as "Browser integrity check".
In the help center I've found this about it:

> The Cloudflare Browser Integrity Check (BIC) operates similar to [Bad Behavior](https://bad-behavior.ioerror.us/) and looks for common HTTP headers abused most commonly by spammers and denies access to your page.  It also challenges visitors without a user agent or with a non-standard user agent such as commonly used by abusive bots, crawlers, or visitors.

Is this something that you can solve?

**Comment by mendhak** [comment]
That's interesting because I'm also using CloudFlare for Custom URL, which is fine, but I've never tried it with NextCloud.  

I am using an OwnCloud library which does the connecting so I'm not sure if there's anything I can do, the fields visible to me in the library are very limited. 

I did notice that the user agent is `Jakarta Commons-HttpClient/3.1` and according to [this thread](https://community.cloudflare.com/t/does-cloudflare-block-some-user-agents-by-default/157326) that might be the reason it's being blocked. 

I think you'd need to create a firewall rule in Cloudflare Dashboard for this.  Under Security > WAF > Create Firewall Rule.  I see the dropdown has many options in there.  Maybe a combination of the NextCloud URL plus the User Agent could work.  But if I ever update the OwnCloud library in the future then the User Agent might change and you'd have to modify the rule.

**Comment by andreapx** [comment]
I did create a firewall rule and it's working!
