### ISSUE TITLE
Most precise settings using Gps only

### ISSUE THREAD

**Issue by blogdemoi** [mendhak/gpslogger#1057]
Hello,

What would be the most precise settings for recording a very detailed track (Gps only)?

Thank you.

**Comment by mendhak** [comment]
I can try to answer but it may not be as detailed as you'd like. 

Go to Performance menu and disable network locations.   
Optionally enable passive locations so that locations obtained for _other_ apps are read here too.  
Set logging interval to 1 second, the app will not go below 1 second interval.   
Keep GPS on between fixes.   

You'll probably want to lower the duration to match accuracy (the app will keep trying for this long to match the accuracy) and the absolute time so that the app gives up sooner and tries again.

**Comment by blogdemoi** [comment]
Thank you.
