### ISSUE TITLE
[Feature request] Several intervalls for different logging types simultaneously

### ISSUE THREAD

**Issue by Minfred** [mendhak/gpslogger#1081]
Hi Mendhak,

first i want to say thank you for your brilliant app! I love it and use it often.
Especially as a tracking device in my car for two reasons:
- Record my routes (via logging to gpx-file and upload it to my dropbox)
- Let my Smarthome (Openhab) know, where the car is (via logging to custom url)

Both working so far, but where the gpx need to be precise (logging every 1-3 seconds), the url-logging just needs a datapoint now and then (maybe every 5mins). In the current state (gpx and url logging every 3 seconds) i need way to much traffic than i can afford.

Is there a possibility to use two different logging intervalls or to filter one logging possibility (logging to custom url just every 100 datapoints of the csv or something like that).
Or is it possible to implement different logging intervalls for each logging possibility?

Thank you for your effort,
kind regards

**Comment by mendhak** [comment]
Hi thanks for that. So it's been requested a few times before, but GPSLogger just isn't built for multiple logging intervals. The problem is the additional drain it would have on battery, but worse than that, the additional complexity on the codebase. Because it's such an old codebase, changing and maintaining things are a lot harder now for me, and I have to keep things simple with the limited time I have. So it could technically be done, it's just going to make things more unstable. That's not the answer you'd like to hear but is the simplest for the codebase (ie, best for longterm)
