### ISSUE TITLE
Upload all files that have failed to upload when network becomes available

### ISSUE THREAD

**Issue by upsuper** [mendhak/gpslogger#1117]
Firstly, thanks for this app. It is great.

While using it, I found that if the phone goes offline, and some files are failed to be uploaded, they wouldn't be uploaded later. It would be great if it can keep a list of files that haven't been uploaded successfully since last time, and upload all of them when there is a chance.

As context, I use this app in a separate device that doesn't have SIM card installed (i.e. no access to cellular network). I use it as a offline location recorder. This device can only connect to the WiFi of my home, and I configured it to upload the files to an internal server accessible only from the local network. I made it so that I don't expose the location to anyone in real time, but can still review the path I've been going through afterwards.

The problem I found in doing so is that, if I go out for several days without going back home, the files of those days are not uploaded. I have to connect the phone and copy out those files manually, rather than being able to rely on its automatic uploading.

**Comment by mendhak** [comment]
Sadly the app isn't clever enough to be able to do that, it's very very stateless, so it doesn't really know about 'other' files except for the one that it's working on, and that's it. I've got no plans to have it track its history including past points and files. 

There is retry logic though, which is supposed to only try uploading when an internet connection is present... but since it's not working for you I suggest to look at a third party application to help you with your specific privacy-focused setup, like Syncthing maybe? That's assuming Syncthing can work with an extended offline setup.

**Comment by upsuper** [comment]
One issue with a third party sync is that the latest file may be broken because the app could still be writing to it while syncing. Is it possible to make the writing atomic, e.g. maybe by writing to another file then move to override?
