### ISSUE TITLE
[Feature Request] Have you a plan to add Kalman filter

### ISSUE THREAD

**Issue by TrueArgus13** [mendhak/gpslogger#1134]
Hi!
Is it possible to add Kalman filter to recording points? It can somehow help with scatter problem caused by multipath. 
I think regular KF is more suitable, then EKF because we can assume GPS system is about linear.

**Comment by mendhak** [comment]
I've got no plans for this since I don't really understand what a Kalman filter is; it's definitely come up in one or two threads before and I've tried reading about it, but I don't understand enough about it to know what it's doing or how it'd be maintained. 

From what I can tell there is one big limitation in GPSLogger, which is that it doesn't keep track of previous points. It keeps track of the most recent point, but nothing before that. So that would get in the way of providing data for any calculations, in turn it might require a local database setup now which greatly adds to the app's burden.

**Comment by TrueArgus13** [comment]
Ok. Got it. Thanks!
