### ISSUE TITLE
GPSLogger doesn't notify the user when it can't write to files, leading to data loss

### ISSUE THREAD

**Issue by JacksonChen666** [mendhak/gpslogger#1138]
Sometimes the permission on my phone gets messed up (no idea why or how, just that it does) and I'll have to re-grant some permissions to apps. I often forget to re-grant the permissions for GPSLogger, since it doesn't tell me when it can't write to a file (when starting a new log), so all logs that are recorded while the permissions are broken just don't exist at all.

I've had this issue happen twice, and it took me at least a month to notice the issues in the first place.

Possibly related to #1053

(/e/OS 1.21.1, GPSLogger v130, FP4, not related to battery optimizations since it's about storage permissions and everything's fine when that's fixed)

**Comment by mendhak** [comment]
I'm currently working on this, at least partially. 

I'm able to create a channel for errors. 

I'm able to send an error notification when all permissions have been denied. 

I'm going to start showing error notifications when file writes fail due to IOException or SecurityException. However, I'm going to try making it a single notification so it doesn't become overwhelming. It could be that each file writer fails and results in a notification but each one overwrites the other... which is a bit weird. Need to think of a way to make this efficient maybe. 

Here's what the notification looks like: 

![image](https://github.com/mendhak/gpslogger/assets/746276/9a462f4e-f7ae-4cd7-936f-59ddcd6c92eb)

I've chosen Visibility Public and Priority High. I'm assuming a user would want to know that their writes or the app is failing? 

I can't do anything if the user denies notification permissions! 

I ran into a really nasty situation where notification permissions were denied while everything else was accepted - I think it's basically this [complex StackOverflow thread](https://stackoverflow.com/questions/73067939/start-foreground-service-after-notification-permission-was-disabled-causes-crash). The app would think it had all permissions and start the service, but because notifications were denied, it would immediately stop the service, and because the foreground service started but didn't show a notification within 5 seconds, it crashes the app, and starts a crash-restart-crash loop. I've modified the stop service code so that if notification permissions are denied it doesn't stop the app. Weird hacky workaround that's going to make zero sense in 1 month from now :cry:

**Comment by mendhak** [comment]
When location or all permissions are denied (except notifications!)

![image](https://github.com/mendhak/gpslogger/assets/746276/519830fc-7bc8-4135-b9f2-592be4b7d871)

**Comment by mendhak** [comment]
So invisible I forgot it was there haha. 

I was using the built-in `android.R.drawable.stat_notify_error` I wonder if there's something else I could do.

**Comment by mendhak** [comment]
There should be one already when you start logging, if the file write permission is denied, then a popup appears like this

![image](https://github.com/mendhak/gpslogger/assets/746276/2f688f55-e8e1-4b81-9823-3d70bf76d665)


And if all permissions denied then that "first time permissions" apologetic prompt should appear already right when the app is launched. Are you not seeing that? 

I didn't realize you meant in-app. I'm wondering I should probably continue anyway with the notifications since it could cover both use cases, in-app and background service.

**Comment by mendhak** [comment]
If anyone wants/is able to test, an APK is here: 

https://github.com/mendhak/gpslogger/releases/tag/v131-rc2

Note that if you use the FDroid version of this app, installing this is like new, so you'll lose previous data and settings.

**Comment by mendhak** [comment]
v131 is in the [releases](https://github.com/mendhak/gpslogger/releases) and [FDroid](https://f-droid.org/en/packages/com.mendhak.gpslogger/)
