### ISSUE TITLE
New version crashes immediately 

### ISSUE THREAD

**Issue by alankjackson** [mendhak/gpslogger#1176]
Pixel 8 phone, Android 15
When I try to open the app, it immediately crashes. I tried clearing the cache, no joy.

**Comment by datoffy** [comment]
I had the same problem after updating via F-Droid on my Pixel 7a.
I solved it by granting unlimited background usage permission in app info -> battery -> background usage

**Comment by alankjackson** [comment]
I already had app battery usage set enabled in background. All permissions are allowed.

**Comment by alankjackson** [comment]
So I just uninstalled and reinstalled the app. Now it is working. Sorry for the noise.

**Comment by mendhak** [comment]
OK that is good to know. 

FWIW I did try to recreate this issue a few different ways, but couldn't get it to crash at all. If someone does encounter this it'd help a lot if there is a way to recreate the issue. The reason to recreate the issue is so I can look in logcat and see exactly which thing is causing the crash. Alternatively if someone encounters this and is familiar with adb/logcat please capture it and post it here.
