### ISSUE TITLE
Sending an Intent with the track statistics

### ISSUE THREAD

**Issue by rsedlac** [mendhak/gpslogger#267]
Please add sending an intent with the track statistics that could be caught by other apps such as Tasker. I'm interested in the distance travelled namely but also the other values could be further processed.
Alternatively, please add the distance travelled figure into the GPX/KML/CSV file.

**Comment by lenucksi** [comment]
This would also be useful to make sharing tracks easier by just passing it off to the configured email / whatever app of choice.

**Comment by unaszplodr** [comment]
I was just looking at the broadcast event in the hope that distance travelled was included as an extra. The ability to set the profile when starting via an intent would also be handy.

**Comment by mendhak** [comment]
I've got a RC1 tag with a test APK here:  https://github.com/mendhak/gpslogger/releases/tag/v126-rc1

There's a new "gpsloggerevent=point" broadcast, and it will contain  `%latitude`, `%longitude`, `%accuracy`, `%altitude`, `%duration`, `%travelled`. These values are raw and unprocessed, and will not respect user preferences. For example the formatting will be decimal only instead of whatever was chosen in General preferences screen.  

It's experimental of course and my main concern as usual is its effect on battery life.  I don't _think_ that adding a broadcast to each fix should cause many problems.

**Comment by unaszplodr** [comment]
I've just tested an HTTP>intent relay for use with Tasker and 'Log to custom URL' this afternoon, which appears to work as expected... I'm only sending %travelled as a GET query, which is not really much of a security concern, but it is perhaps worth noting that exposing location data via open broadcast is potentially very hazardous! I know Tasker cannot intercept broadcasts that specify a packager, but I wonder if it can receive broadcasts when net.dinglisch.android.taskerm is specified?

Either way, if it were my choice, rather than creating a new broadcast to be emitted upon recording each point, I would simply append the parameters to com.mendhak.gpslogger.EVENT, whereby the user can request them with the getstatus extra. This will have less impact on battery life, assuming the user doesn't spam GPSlogger with broadcast requests!

All that said, simply adding the raw values for total duration and distance to com.mendhak.gpslogger.EVENT might be a more prudent, battery and security-wise.

**Comment by mendhak** [comment]
Yeah those are good points, I'm glad you pointed it out.  I was wondering about the battery and the use of broadcasting so much 'noise'.  Making it a result of getstatus could be good.  Just get it when the user's workflow needs it.  

I will scale this back.  

- [ ] Remove lat long altitude (Oops, went a bit overboard there)     
- [ ] Remove the new event type   
- [ ] Make duration/travelled part of the existing event broadcast

**Comment by unaszplodr** [comment]
Thanks for the revised features! Please could you trigger a pre-release build so I can give them a spin?

**Comment by unaszplodr** [comment]
Ah, sorry, I hadn't realised you'd built another RC1!

**Comment by mendhak** [comment]
v126 is now in [releases](https://github.com/mendhak/gpslogger/releases/tag/v126) and [fdroid](https://f-droid.org/en/packages/com.mendhak.gpslogger/).
