### ISSUE TITLE
FIFO buffer for CustomURL

### ISSUE THREAD

**Issue by ambrosa** [mendhak/gpslogger#303]
Sometimes I ask again to you for transmission FIFO buffering during CustomURL transmission.

This can help if you are recording your trip to a real-time server (i.e. my motolive.zapto.org server) and during a trip (i.e. with car or motorcycle) you loose 2G/3G signal for some minutes (because you are into a long road tunnel or in the middle of mountains). 
GPSLogger should save unsent data into a simple buffer (i.e. a simple array) and when data can be sent again, all data saved into buffer are uploaded remotely (and buffer is now empty).

I asked this in issue #195 :
*Is it possible in Android to set a static array (like C, an array that doesn't loose it content) ?
If answer is yes, set a sized FIFO memory buffer. About 50 or 100 KBytes is enough. Or limit it to a maximim number of entries (1000 records ?). If buffer is full, oldest data are deleted and newest data are recorded. Obviously you can loose some data (but full data are available into GPX/KML file if enabled).
Add a simple static FIFO buffer into CustomUrlJob.java  public void onRun() function. 
Add en external loop to onrun() try / catch main code. The loop check if buffer is not empty and run many time the try/catch code.
If website is not reacheable (or it's answer is not 200 OK), the catch code add parameters into FIFO buffer.
If website is reacheable and its answer is 200 OK, looping try/catch will send over and over again URL until buffer is empty.*

Really, it's a very simple change to your code. I cannot do it myself because I've never write Java code and I've never programmed with Android.
Are only a dozen rows of Java code , more or less :-) :-) :-)

**Comment by mendhak** [comment]
This should already be done - I am using the [android priority jobqueue library](https://github.com/path/android-priority-jobqueue) for any data-related activities, for example [custom URL](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/customurl/CustomUrlJob.java).  This includes Google Drive, Dropbox, Custom URL, OpenGTS, FTP, Email.  Each time there is something to perform, a `Job` object is created and submitted.  The job only gets executed when the network is available on the phone, otherwise it sits and waits.  I believe it gets serialized to disk so it persists even if GPSLogger is killed and reopened.
