### ISSUE TITLE
Strange data logged

### ISSUE THREAD

**Issue by visintinl** [mendhak/gpslogger#304]
I've used a few times GPSLogger, tracking my walks in hills and woods, but quite often there is some very strange track in the middle of those "valid". I mean: after saving the .gpx file and loading it in Google Earth i find the correct track, but suddenly it jumps to a distant location (some 10km away) then it comes back to the real location. I can't understand so I'll attach two images.
The first img (gpslogger_1) contains only the original recording from GPSLogger, while the second has the correct one overimposed. I did edit the original, deleting the "invalid" recordings. I can send you the original .gpx file if needed.
Thanks a lot for your attention.
Luigi Visintin
(visintin@inrete.it)
![gpslogger_1](https://cloud.githubusercontent.com/assets/11878527/7078961/f5cc9910-df1e-11e4-8af4-a2da31d6273c.png)
![gpslogger_2](https://cloud.githubusercontent.com/assets/11878527/7078960/f5c667f2-df1e-11e4-8052-e41e6678907f.png)

**Comment by mendhak** [comment]
I've seen this a few times when walking in hilly or "remote"areas. Cell tower locations will jump around quite a bit because there isn't much to triangulate on for the gps chip, what you see is its best guess. Instead what you can do is go to the location listeners and uncheck the network location listener and passive too. This will tell the app to only listen for gps satellite based locations. 

You can also set an accuracy filter so that any points which don't have an accuracy of x don't get logged to file.

**Comment by visintinl** [comment]
Hi,
thank you very much for your quick answer. I'll try next time I do a 
walk using your suggestion.
Cheers
Luigi

Il 10/04/2015 08:30, mendhak ha scritto:
