### ISSUE TITLE
New file is uploaded to osm for every point logged

### ISSUE THREAD

**Issue by mvherweg** [mendhak/gpslogger#306]
Updated today on my Nexus 4.
Since then, it is uploading the file after every new point being logged.
Note that it is not a new file, but every time the same file with 1 more point than the last.

**Comment by mendhak** [comment]
What's the file name that you're using?  Is it a custom one with `%MIN` in it?

**Comment by bskbo** [comment]
I think I'm experiencing a similar issue.

Using "allow auto sending" for emails, "how often" set to 1440. Instead of receiving an email once a day, or when the file name changes (also once a day) I receive an email with every new point.

Not using a custom file name. I do use the device serial prefix.
