### ISSUE TITLE
Send data to CartoDB server

### ISSUE THREAD

**Issue by hetlelid** [mendhak/gpslogger#310]
It would be really nice to be able to send position data automaticly to a cartodb.com server. This for realtime tracking and other GIS purposes.

I know about the url send function, but there is no way to debug if the send fails..

**Comment by mendhak** [comment]
I think I can have a look at this at some point.

Do you know of any other services like CartoDB where a user would want their location logged?

**Comment by hetlelid** [comment]
Thanx for your comment. CartoDB is a opensource package, and very powerful. If you add this feauture, please consider what to do if the send fail due to no internet connection. Preferably upload later. What happen if the url-send fails because of no internet connection? Will it re-send later?

**Comment by mendhak** [comment]
I'm already using a library which waits for a reliable internet connection before performing data activities, so that bit is easy.

**Comment by hetlelid** [comment]
Also, i have to say iæm very thankful for this excellent app!! :) For my part i now got the send by url function working. There should maybe be a degug function to print the error reply from the server. I figured out that i can't use https, or have any space in the url, has to be urlencoded (%20). (This is not a problem as i now know it) The cartodb apo url is like this: http://{account}.cartodb.com/api/v2/sql?q=INSERT INTO test_table (column_name, column_name_2, the_geom) VALUES ('this is a string', 11, ST_SetSRID(ST_Point(-110, 43),4326))&api_key={Your API key}

**Comment by mendhak** [comment]
Have a look at the general settings where you can enable a debug log.  it logs some debug info and error messages.  Your troubleshooting would be to try the URL and look at the file.

Alternatively if you are rooted, use logcat and you can see the messages being printed.

**Comment by zotz** [comment]
"Do you know of any other services like CartoDB where a user would want their location logged?"

So, I have developed / am in the middle of developing a little app inventor app the updates a postgis or mariadb database via a php script. The app inventor app posts the info for one "location snapshot" - location coordinates and speed are the key data and the pgp script inserts the data into the database table.

Then an openlayers based html page displays a map and includes a  vector layer / feature layer that is based on data pulled from the sql database via another php script called with jquery.

For me, this is a deep rabbit hole I have gone down.

I am here because the performance of the app inventor app leaves a lot to be desired. I think this may be largely due to my ignorance and poor "coding" but also due to limitations of app inventor. I was searching for a Free Software android app (would like iOS too) that could do a better job. I found gpslogger but have not installed and tested it yet. Perhaps before the week is out.

I am hoping that the log to custom url function may be of some use to me or may give me some hints as to how to modify the code to be of use to me. I am interested in the ability to begin running on phone boot, in the design to be battery efficient, in the ability to run in the background. I think I need "real time" remote logging rather than local logging with a file containing multiple point being uploaded intermittently.

The "grand idea" behind what I am attempting is to be able to display "traffic snapshots" during rush hours etc.

I have been playing a bit with qgis the last 2 days. I have been looking into WFS and WFS-T.  There are so many TLAs and FLAs in my head I don't know if I am coming or going.

So, I would want to log to a custom service. I think I have seen other services mentioned but I did not bookmark or pay careful attention as I was searching with other priorities.

**Comment by mendhak** [comment]
Although I had said I'd look at making it its own feature, the debugging feature with Custom URL now exists.  It is simpler for the app to just have Custom URL logging - log to Carto DB - and product a debug log if there are any problems:  https://gpslogger.app/#troubleshooting

So for that reason I will close this issue

ALso thanks for your update
