### ISSUE TITLE
logging breaks after each update

### ISSUE THREAD

**Issue by lvmm** [mendhak/gpslogger#314]
I've got GPS logger set up to create gpx tracks in the default folder (/storage/extSdCard/Android/data/com.mendhack.gpslogger/files) and upload them automatically to google drive when logging is stopped. GPS logger has been updated quite a few times recently and after each update logging broke down - no logs were created in the folder even though GPS logger appeared to be running and showed the icon in the status bar. Uploading a test file from GPS tracker to google drive worked and resolved the issues until the next upgrade so this issue is possibly drive- or auto-upload related. Starting and stopping is done via desktop widgets, Samsung Galaxy S5 duos with lollipop, GPS logger was not running when it was updated.

**Comment by mendhak** [comment]
Did it show you a location in the status bar or just say "GPSLogger is still running..."?  

Did it actually create no files or did it create a file with a little info and just pause after that?

**Comment by lvmm** [comment]
I start/stop GPS logger with desktop widgets and the only thing I check is whether the GPS logger icon appeared on the top statusbar so I cannot answer the first question but I always run it together with a map, so I can tell that I had GPS fix while GPS logger was runnig, and yet no files were created at all.

**Comment by mendhak** [comment]
I'm wondering if the bit with GDrive upload is a red herring.  Due to the intermittent nature, I'd suggest next update you enable debug logging (general menu) and start the logging.  Check the status to see if it says that it's simply running or it shows a location.  If it doesn't, let it go for a while, then stop it and send me the debug log and I can have a look.  Unfortunately the next update wont' be for a while

**Comment by mendhak** [comment]
Took a while but fixed here: https://github.com/mendhak/gpslogger/issues/497
