### ISSUE TITLE
Notification when no fix is acquired over time

### ISSUE THREAD

**Issue by infernix** [mendhak/gpslogger#318]
I've got a spare phone where I'm turning off wifi/bt/sync, don't have a sim card in it, run it on airplane mode and underclock the CPU. GPSLogger seems to do up to about 30 hours on it which is good enough for me. I am actually keeping the GPS on between points and it seem to draw around 75mA only; with an extended battery I could probably go for a week this way. 

However, I would like it to notify me with an alarm type notification if it isn't working correctly. 

I am thinking of it in a time limit sense; for instance, if no fix has been acquired in the last X minutes (configurable), notify me with an alarm until I dismiss it (to maybe reboot the device, or otherwise check what's going on). 

There may be other/better ways to determine that it isn't working correctly but that would make most sense to my use case where I use GPS only and have it active all the time.

Would this be possible to implement?

**Comment by mendhak** [comment]
Could you use Tasker to do something like this?  A file event (File Modified) which records last update time.  and another event which checks if the %gpxlastmodified time is greater than `x` minutes, it alerts you.

**Comment by infernix** [comment]
That's certainly possible and not a bad idea, though still nice to have built in since I don't need anything except gpslogger on that device; not even Google apps. 

I'll leave it up to you to decide if you want to add it to the code :)

**Comment by mendhak** [comment]
With the advent of Marshmallow, this idea has now been killed - the OS itself suspends the application and can also interfere with the time-interval that a user specifies.  This means that the application cannot self diagnose correctly.

Even using an external application to inspect the log file is not reliable because such applications are subject to the same rules under doze mode.  Closing this now.
