### ISSUE TITLE
feature request: log the cell id

### ISSUE THREAD

**Issue by ag88** [mendhak/gpslogger#319]
could the gsm / umts / lte cell ids e.g. for gsm/umts normally there would be mcc (country code) /mnc (network code) /lac (local area code) / cellid (the cell id)
be logged for gps fix as well? 
This could be useful as a means to contribute data to mozilla location service
https://location.services.mozilla.com/ 
or opencell id
http://opencellid.org/

**Comment by mendhak** [comment]
The only way I can see this happening is if I delay each point being logged to the file so that the cell tower lookup can happen but that would break too many things.  This info doesn't arrive as part of `LocationManager` updates unfortunately (it should!) so this means a separate thread just to keep track of current towers using another server; it's basically not a good fit for the way GPSLogger is doing things.
