### ISSUE TITLE
udp logging request

### ISSUE THREAD

**Issue by danielrbjo** [mendhak/gpslogger#321]
Wondering at the level of effort needed to add udp logging to remote server capability. Need to reduce the TCP/HTTP connection overhead when logging at once per second which is needed for our use case. Willing to fund some effort if necessary.

**Comment by bostikmxb** [comment]
Wondering too ;)

Interested in UDP update ... seems not working or didn't understood how to set opengts to receive it

Thanx

**Comment by mendhak** [comment]
Do you mean UDP logging to a custom server (like custom URL logging) or UDP logging to OpenGTS?

OpenGTS UDP should be working, but does require going through their massive [installation doc](http://opengts.sourceforge.net/OpenGTS_Config.pdf) and settings things up.  

The string sent looks like so:

    acct/device/$GPRMC,103025...........

**Comment by danielrbjo** [comment]
Looking for UDP logging to a custom server, similar to the custom URL logging, but with UDP instead.
Thanks,
Dan

**Comment by ray63** [comment]
I have tried to use UDP transmission to OPENGTS using the 'out of the box' template server, but note an error DCServerFactory._loadDeviceByPrefixedModemID:2507] !!!UniqueID not found!: 

Looking at the TrackClientPackerHandler code of the template server, it  appears as though the syntax required is
MobileID,YYYY/MM/DD,HH:MM:SS,Latitude,Longitude,Speed,Heading,AltitudeM

whereas GPSlogger sends a GPRMC formatted message.

I've never coded in Java before, and haven't set up any IDE's for JAVA.  Has anyone got an OPENGTS server script that handles UDP data from GPSLogger they can share or point me to?  I'd like to stand on someone else's shoulders, rather than having to start off the ground, so to speak.

**Comment by mendhak** [comment]
Did you specify all fields in the OpenGTS screen - including account id and device id?

**Comment by ray63** [comment]
Yes, the account id and device have been set up and work for http.  Changing the port and protocol to UDP doesn't work with the same settings using the 'template' server for the reasons mentioned.
