### ISSUE TITLE
Improve accuracy by dropping points that jump too fast

### ISSUE THREAD

**Issue by DavyLandman** [mendhak/gpslogger#328]
I like the logger a lot, but there are some accuracy issues, sometimes the gps isn't that sure yet on the first fix, (I suspect the accuracy in meters isn't always right?).

So I was thinking, what if you could tell the app that you are walking, in that way it knows you'll most likely not be going more than 10km/h? Similar for running or biking, there are certain limits that could help in dropping noisy points.

The difficulty would be that if you would get on a bus for example, and then continue, it should only drop the bus points, and afterwards the points are again close enough to each-other, so it can continue.

**Comment by dbareis** [comment]
It could also look at before and after points to decide on whether the middle one needs to be dropped.

**Comment by mendhak** [comment]
Made an attempt now - although not going as far as asking the user for a maximum distance/time as that may open up a whole avenue of extra overheads.  Basic check here is ensuring we're less than 600 km/h based on distance/time of 'this' point and the last point.  Will tweak more in the future.

Another option was attempting to figure out a maximum speed based on Activity Recognition but that doesn't exist on every device and further is not guaranteed to be correct at the *time* of calculation.

**Comment by dbareis** [comment]
Why not do as I suggested and look if the user effectively backtracked
(look at points either side to determine if the point being examined "makes
sense", no need to look only at speed.

**Comment by mendhak** [comment]
There's no rewind-ability.  A point gets written to file or sent to URL and can't be recalled.  So if a new point is received and then it's decided that the previous one was not a nice point, it's too late.  To allow for rewinding would require not writing files, only exporting files and also storing all points in a database. 

Instead this problem is normally solved using something like [Least Squares](https://en.wikipedia.org/wiki/Least_squares) or [Kalman filters](https://en.wikipedia.org/wiki/Kalman_filter) to figure out if the next point falls within 'expected' ranges which itself is non-trivial and also requires storing all points alongside writing them to file.  The weird bit though - most GPS hardware on our phones already apply Kalman filters.  We should - theoretically - not be seeing jumps!

**Comment by mendhak** [comment]
v81 released to market
