### ISSUE TITLE
Upload only when connected to WiFi

### ISSUE THREAD

**Issue by AlwindB** [mendhak/gpslogger#336]
After for some unknown reason the application burned 400mb from my datalimit a new nice to have would be that the program uploads when connected to WiFi. Similar way Photos or One drive works.

Other solution would be to sync manually/bulk when not on a mobile data connection

**Comment by mendhak** [comment]
For this I'll have to implement a custom [Network Utility](https://github.com/path/android-priority-jobqueue/wiki/Job-Manager-Configuration) which reads from shared preferences.

Sample network utility [here](https://gist.github.com/mecid/1e5dc9a41ed413c99121), could modify to check for Wifi State rather than a ping.

**Comment by mendhak** [comment]
v66 released
