### ISSUE TITLE
Massive data usage problem

### ISSUE THREAD

**Issue by MinchinWeb** [mendhak/gpslogger#344]
First off, thanks for the great app! I've been using happily for over 3 years now!

Over the last month, I took an international trip, and the app reportedly used massive amounts of data. My setup was like this:

- GPSLogger runs continuously on my phone
- GPSLogger is set to log to GPX, create a new file every day, log not more than every 20 seconds and with a minimum distance between points of 10m, and set to upload to Dropbox every 60 minutes and when I stop logging
- my phone doesn't have cell data (international roaming was way too expensive), but I would sometime tether my phone (via wifi) to a friend's phone who did have cell data.
- their phone data would go in and out, depending on cell reception

Over the two weeks of the trip, my phone reported that GPSLogger used over 5GB of data!

![img_0671](https://cloud.githubusercontent.com/assets/1548809/9391275/195dc0a8-4733-11e5-9a89-cf25454fdc22.JPG)

However, not all of that went through. Here is the data usage for tethering from my friend's phone:

![screenshot_2015-08-18-22-34-11](https://cloud.githubusercontent.com/assets/1548809/9391314/4c0ebf3e-4733-11e5-83cd-2224fb1da12a.png)

As well, when I crossed back into my home country and turned on my own data again, GPSLogger uploaded 250MB of data inside 2 hours!

![2015-08-19 01 12 06](https://cloud.githubusercontent.com/assets/1548809/9391332/6e3f8764-4733-11e5-8b7d-13708a104d4f.png)

By way of comparision, the GPX files created over the 2 weeks of this trip total 1.29MB.

Any idea what is going on, or how to prevent this much data usage?

**Comment by mendhak** [comment]
The way these uploaders (Dropbox, GDrive, OpenGTS etc) work is when the interval is up they attempt to upload.  If an internet connection isn't available, then it will wait.  When a connection becomes available all pending tasks are executed.  If the upload fails it will retry and I believe the default retry is 20 times.  

I think what's happening here is that the tasks are accumulating; when a connection becomes available, all of them execute.  

What probably should happen to minimize this is on each task being queued up, all previous tasks should be cancelled - since they essentially upload the same file.  

Also - in v66 there's now an option to upload on WiFi only.

**Comment by MinchinWeb** [comment]
Thanks for looking at this right away!

**Comment by mendhak** [comment]
v67 released
