### ISSUE TITLE
Some feature requests and suggestions

### ISSUE THREAD

**Issue by solyaris** [mendhak/gpslogger#359]
Hi Mendhak, all!

First of all let me thank you because your Android app EXCEL!
Very very well done both in terms of features, and presentation.

I sent a 5 star rank in google play  https://play.google.com/store/apps/details?id=com.mendhak.gpslogger

Also this project readme is great beacuse you show very well how to build up all! 

Here below a mix of suggestiones/change requests/thoughts. Not real issues, so close this if you prefer!

## 1. Donation / payment (business model suggestion)

We are here and so your project is also open source. Great!
I invite you to take donations not just with bitcoins, but maybe with mor common payment gateway donation as Paypal...
I think that your app is so well done that it deserve a payment for download, even if open source. ut maybe there is some "contradiction" in terms of licence. I don't know but my statements here if to share with you my appreciation.

## 2. Download with automatic configuration (possible change request)

Your app is  really complete in configuration options, and a bit complex also fort an IT guy.

Please consider the scenario where you are a supplier of some service to not expert people. 
Right now they have to go to google play, download the app and do a not so intuitive configuration for some specific fine-tuning needs.
In my case I would realize some back-end application server that track people and I would use your feature that in real-time send coordinates to a custom URL (already tested, excellent again!)
So in the describe case I have also to configure carefully the URL and some other configurations.

My naif question (maybe not directly related to your specific app) is: there is a way to build up an "invitation" behaviour so I could send by example some HTTP link containing all a non technical user need to download (from Google Play) and get the app configured with some Preset configuration (by example containing all data to set in the device the performance tuning settings and the URL to send data ) ?
In other words, my request is that app could "download" a configuration file ... 
All this make sense ?

## 3. Share Intent to Gmail: Google Maps vs  openstreetmaps (change request)

Now, in my phone If I click on the icon in the down menu at right, I can share intent and I can select Gmail (mail client installed).

Gpslogger in this case prepare a mail containing by example something like:

    http://maps.google.com/maps?q=44.4101087,8.9589158
  
That's fine (using Google Maps) but I'd love to instead use OpenStreetMap as default locations viewer, in that case the above link could substutute with something like this one:

    http://www.openstreetmap.org/?mlat=44.4101087&mlon=8.9589158&zoom=18
   
That's a minor point, for sure. But please note openstreetmap is fully "compliant" with the open source philosophy; Google ... so and so :)
Seriously, openstreetmap in my city as you could imagine: Genova, Italy, count a growing up community and maps are pheraps more detailed in comparison with Google Map. No polemic, just a verification.

## 4. Cella antenna location slow (minor issue/ request)

I just start doing some test but I just noted that the localization using just cell operator antennas (great feature in some case and for battery usage saving, Thanks again for your specific attention on this!), require a lot of minutes, in case I move by example with car in a new location.
I do som tests with a Samsung S2 phone, with Android 4.2.2.
I read in the FAQ you mention points: "the long time to find a fix" and the "interval time passed without lany log". But it seems you talk about cell network localization specifically. 
Maybe could help some front-end advise (and also in the realtime HTTP GET ) to point out "no data available by cella phone" or "getting coordinates from cell antennas" someting like that.
 
## 5. Logging at scheduled intervals ("crontab" like). Minor request

It could be helpfull to let configure some fixed times in a day where the tracking must be active. Maybe in coincidence with working time. Eg. Every week, Monday to  Friday, from 8 A.M. to 5 P.M. 
Maybe with a crontab syntax.

## 6. Statistics about power consumption and  tracking accouracy in different location input: GPS/WIFI/Cellular Antennas.

Do you pheraps did some test to compare performances related to 
- power consumption
- tracking accouracy

in three different scenarios 
- GPS
- WIFI
- Cellular Antennas
- Merging above 
?

I'm very interested in a super-efficient battery usage.

Sorry for my long write, that's my contibution, I hope.
Respect
Giorgio

**Comment by mendhak** [comment]
Ah better late than never...

I did experiment for a few months (when I saw your post back in Oct) by replacing the current donation links with paypal links.  After 2 months  I got 0 - I believe this is because Google specifically don't allow Paypal integration in apps (bypassing their own payment system) and so you are forced to take 2-3 steps to actually get to a Paypal.  Changed it back now :D

I don't have an easy way to do automatic configuration.  There are *some* ways.  If you install this app on a user's phone and the phone has a "gpslogger.properties" file at the root, then those settings are set for them automatically.  A few users have told me they use it when they control the phones and need to distribute the app to people.  Having the app modified so that it goes to a specific URL on load, can be done, it'd be a custom app for that specific organisation.   I have done this before, here's an [example](https://play.google.com/store/apps/details?id=com.mendhak.gpsloggercda).  

Good idea to also link to OSM.  Can make this a preference.

For the schedules, I'd suggest looking at Llama or Tasker instead, control the invokation externally. 

 I've not recorded stats in different scenarios, just lots of testing.  It's always been a matter of better battery life = worse accuracy and vice versa, although I do try to put the GPS to sleep between intervals.

Anyway I'm doing a cleanup of the issues right now as they've been accumulating, so going to close this one but feel free to continue if got questions

**Comment by Mntkeep** [comment]
> Good idea to also link to OSM. Can make this a preference.
> 

> Anyway I'm doing a cleanup of the issues right now as they've been accumulating, so going to close this one but feel free to continue if got questions

Sorry if I missed it, but I don't find an option to change the map provider from default Google Maps to OSM when sharing the location.
