### ISSUE TITLE
Annotation actually creates a Way Point (sets "name", probably should set "description")

### ISSUE THREAD

**Issue by dbareis** [mendhak/gpslogger#373]
I'm viewing the waypoints in another app and its not 100% happy so I started looking into the issue, I think that the "name" should be a fixed value for the type of waypoint (say "GpsLogger") and its the description field that contains the text, that way the waypoints can be visualised with pins when viewed on a map. 

From what I can see If we could define our own "types" say "playground", park or "stay away" etc, then these can be configured to display in different types and colors of pins.

It seems to me that "annotate" should be renamed "waypoint" and perhaps support other waypoint properties.

The current "annotate" could become "notes" or even stay the same but change the track description field instead.

**Comment by dbareis** [comment]
Being able to add a track and describe it would also be great

**Comment by mendhak** [comment]
I've deliberately kept it as generic as possible, this is because no two individuals are using the same app for working with their GPXs.  So some of the changes (define type/color) you're asking are extremely bespoke and custom to your purpose.  I'm not sure what the confusion is, but annotation is simply a layman's way of saying to add a note, not a lot of users understood what waypoint meant (back when it was called waypoint).  

However, the annotate dialog box could very well contain two fields - a name and a desc - makes for better pins so that's a good idea.  I will need to try out a few UI ideas.  For example this can be a collapsed textview which has to be deliberately opened if a `<desc>` is wanted.  Annotations are meant to be as quick as possible, don't want to slow the user down.   Cheers
