### ISSUE TITLE
Feature request: HTTP upload and HTTP POST

### ISSUE THREAD

**Issue by OgreTransporter** [mendhak/gpslogger#377]
It would be nice to upload logs to a HTTP site (e. g. http://php.net/manual/en/features.file-upload.post-method.php).

**Comment by mendhak** [comment]
In the same vein - the Custom URL logging can be an HTTP POST, let users pick.

This will mean the Custom URL 'dialog' should become a proper screen with choices.

For HTTP POST, need to make sure that the variables are sent as body params rather than querystring params.

**Comment by export-mike** [comment]
just wondering is there a way to get this to log in bulk? its likely for my usecase I'm not going to have online access, so maybe be able to do HTTP post with the upload button but to a custom http server

**Comment by lenucksi** [comment]
A "bulk upload" scenario where the entire track would be posted e.g. to some URL at the press of the stop button would be useful to me too. One could just POST the GPX representation of the track plus some additional parameters e.g. the metadata to a URL then.

**Comment by eneiluj** [comment]
@mendhak Are you still opposed to add the ability to upload to custom server URL with POST method ?

My concern is about privacy. I would really appreciate if all was sent in POST data so that if HTTPS is used, the information would be encrypted.

I wrote a Nextcloud app which receives, stores and display live geolocation information from many devices. For the moment there are several ways to log the position (android-side) : 

* a web page accessed with HTTPS which uses leaflet locate method and sends POST requests (safe, not battery-friendly)
* OsmAnd "gpx recording" addon which is able to log with HTTP(S) GET request (not safe, more or less battery friendly)
* GpsLogger custom URL HTTP(S) GET (not safe, battery friendly)

Receiving empty values for some variables (if not available) would not be a problem. The log process would be tolerant to missing values.

The perfect associated feature would be to let user add extra POST variables. In my case it would be the authentication information.

**Comment by mendhak** [comment]
Not opposed to it, just needing to find time to do it - it's a restructuring of the Custom URL screen and some extra steps afterwards. 

Note that HTTP encrypts querystring parameters  as well as body as well as headers, it's not safer or less-safe in that regard.

**Comment by eneiluj** [comment]
Thanks for your answer.

Don't worry, i decided to make it myself.

One question thought : Do you prefer that i duplicate CustomUrlJob and CustomUrlLogger to make a "post" version and choose which one to call in FileLoggerFactory depending on new "post" option value ? Or that i choose which method to use in CustomUrlJob depending on option value ?

I will just add one checkbox to choose POST method in the custom URL parameters. The parameters name will be deducted from the URL settings value. I'll make a pull request soon.

BTW : I think GET parameters can't be encrypted as they are in the query URL.
```
GET is less secure compared to POST because data sent is part of the URL
```
from https://www.w3schools.com/tags/ref_httpmethods.asp

**Comment by mendhak** [comment]
That's a misleading page - it's about HTTP the protocol only; with HTTPS (transport security on HTTP) the client (app/browser) first establishes a connection via TCP CONNECT and then starts sending data after the handshake.  You can verify it yourself -
  have something like Fiddler listening in to an HTTP URL and see how you can't decrypt it without being a man in the middle. 


So about HTTP POST - I had two ideas in mind.  One idea was to provide another text entry where the user could define the body.  The second idea was what you are suggesting - figure out what the querystring params are and make it an `a=b&c=d&e=f` type body.  

Ideally can you make it the same CustomUrlJob with whatever extra parameter to indicate it's an HTTP POST

**Comment by eneiluj** [comment]
Ok thanks for the explanation details ;)

I first added a text entry to specify the POST parameters and after using it, i though it was redundant with the GET parameters in URL field. So i parsed the querystring to get POST parameters names and values.

Ok, i did you say, just a parameter telling CustomUrlJob if it should use POST method or not.

The pull request is on its way.

**Comment by eneiluj** [comment]
I found [this](https://stackoverflow.com/questions/2629222/are-querystring-parameters-secure-in-https-http-ssl#2629241) that adds a little precision about HTTPS and GET parameters. They are actually encrypted as @mendhak said, but a classic advice is to avoid that because sensitive data might be saved in web server logs (like passwords).

**Comment by mendhak** [comment]
Oops.... we missed a trick - eneiluj has created a pull request for this - https://github.com/mendhak/gpslogger/pull/574

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*

**Comment by mendhak** [comment]
Reopening this - currently I'm working on [a branch - customurlplus](https://github.com/mendhak/gpslogger/tree/customurlplus) where the user will be able to specify the body, headers and http method themselves.

![image](https://user-images.githubusercontent.com/746276/34082451-8e91cb5a-e356-11e7-8050-af01d7b719d9.png)


[APK](https://drive.google.com/file/d/1RUeyv6fBk331wRZ4_ot-8I8lWzFZGwB_/view?usp=sharing), [signature](https://drive.google.com/file/d/1v7x5pkcm4KoURwX92PyIeqxiYCdWSzPE/view?usp=sharing), [checksum](https://drive.google.com/file/d/1Cl5-BwoY4_kcUxdJWrcVH6sIWJSEgT7u/view?usp=sharing)

**Comment by mendhak** [comment]
v91 is released to market.
