### ISSUE TITLE
Enable only GPS in data providers by default

### ISSUE THREAD

**Issue by naoliv** [mendhak/gpslogger#387]
I always recommend gpslogger for my friends to record their tracks, but I see one recurrent problem: since multiple network providers are enabled by default, the recorded track isn't continuous nor makes senses sometimes (since it records points very far from the original location).

For example, [this track](https://github.com/mendhak/gpslogger/files/148670/20160226.txt)

Could we have only GPS enabled by default?

Or, at least, at the first time the user start gpslogger, it could explain the use cases, advantages and disadvantages of each mode and make it clear that if he wants to have the most 	accurate track, he needs to select only GPS.

**Comment by mendhak** [comment]
That's the fused location provider acting up; unfortunately this is due to stale data on Google's own servers as those specific locations are based on wifi/APNs and can act differently over time.

I'd probably want to disable fused provider at least - I think I will do this now. It has been a constant source of problems similar to what you are showing here.

As for GPS-only, whenever I change this setting I get asked to switch to the other, no real consensus.

So asking the user does feel like a better idea.  Or I can try this with fused disabled and see if it crops up again.

**Comment by mendhak** [comment]
[Release v72](https://github.com/mendhak/gpslogger/releases/tag/v72)
