### ISSUE TITLE
number of satellites in view is used in gpx output instead of numbers of satellites used to compute fix

### ISSUE THREAD

**Issue by tsteven4** [mendhak/gpslogger#402]
both 1.0 and 1.1 gpx define the sat element to be the Number of satellites used to calculate the GPS fix. (not number of satellites in view).

The easy fix is just to modify GeneralLocationListener to count the numbers of satellites used in the fix using GpsSatellite.usedInFix().  There is also are comments in GpsLoggingService and Session that states we are tracking the number of visible satellites, not the number of satellites used in a fix.  Note that a fix along these lines will correct the gpx usage, but it will also change the count used by CustomUrlLogger.

**Comment by mendhak** [comment]
Nice find, can't believe I missed `usedInFix`. The `Location` object is also supposed to have a `satellites` extra, [bundled in](http://developer.android.com/reference/android/location/Location.html#getExtras\(\)), but some phones aren't patched and some manufacturers don't pass it along (which is why the current way you see it emerged).

So this gives us two ways to do it.  For safety, I'll bundle the `usedInFix` value to maintain a visible count, and also use the bundled `satellite` count.  This way, it's all part of the `Location` object, and none of the views are disturbed.  CustomURL gets the bundled version too.  Also, renaming the Session object's satellite to say it's a visible count.  Also a few constructors get cleaned up.

**Comment by mendhak** [comment]
[Release v72](https://github.com/mendhak/gpslogger/releases/tag/v72)
