### ISSUE TITLE
Points, mid track, will randomly jump miles from where they actually should be.

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [mendhak/gpslogger#417]
I don't really know how to describe it other than what the title says.

I've been using GPSLogger for years.  Recently, tracks will track fine, except randomly, in the middle of the track, certain points will be logged dozens of miles away from where they should be.  I've attached an example.  I can record more tracks as examples if needed.

Github doesn't allow gpx files, so I converted my upload to a txt file.
[20160322.txt](https://github.com/mendhak/gpslogger/files/186396/20160322.txt)

**Comment by mendhak** [comment]
I can see what the problem in this case is - cell networks along the way reported bad positions but said they were of good accuracy *or* were of bad accuracy but recorded anyway.  You can go to Performance setting and under location providers, disable network so that it's GPS only.  

Can you also check in performance settings, what is your accuracy filter, is it 0?  Try setting it to something better like 30-50. 

I think these two factors combined may be contributing to the jumping you're seeing.  I think that the points really far away are reporting an accuracy of (example) 800 or something ridiculous but the app recorded it anyway because accuracy filter is 0 (trust everything) . 

What I can do is change the default from 0 to... 30.  

There is a more scientific approach that uses [Kalman filters](https://en.wikipedia.org/wiki/Kalman_filter) but it's definitely complicated.  Basically I'd have to look at the point I just got, compare it to the previous point to see if it fits in with variance and if it's almost sort of kinda close enough, accept it.  It doesn't work over large times due to variance decay.

**Comment by ChrisThompsonTLDR** [comment]
Awesome, thanks for the response.  Accuracy filter was set to 0.  I changed it to 30.

I had GPS and Network selected, but changed it to just GPS.

Let me know if I can provide any more data to help with this.

**Comment by mendhak** [comment]
v75 released to market.
