### ISSUE TITLE
Not logging

### ISSUE THREAD

**Issue by Alberto2712** [mendhak/gpslogger#447]
Hi,
I ve been using gpslogger for some years without any problem.
But for 2 or 3 months, not all points are logged when I dont set to let gps enabled between points.
In average, less than a point on 10 are logged.

I ve tried different setings, and I have always the same problem, lots of points seem to not being logged.
But when I check the option to enable gps between points, each point is then correctly logged (for example a point each 2 minutes).

I ve got a samsung S6 

Thanks,
Regards,

Here is a sequence in log file, after a correct point at 18h56, then no correct point till 19h16  :
18:56:35 DEBUG GpsLoggingService.stopGpsManager:635 - Removing towerLocationManager updates
18:56:35 DEBUG GpsLoggingService.stopGpsManager:640 - Removing gpsLocationManager updates
18:56:35 DEBUG Kml22WriteHandler.run:213 - Finished writing to KML22 File
18:56:35 DEBUG Gpx10WriteHandler.run:227 - Finished writing to GPX10 file
18:56:35 DEBUG GpsSimpleViewFragment.onWaitingForLocation:474 - false
18:56:35 DEBUG GpsLoggingService.setAlarmForNextPoint:912 - Set alarm for 120 seconds
18:56:35 DEBUG GeneralLocationListener.onGpsStatusChanged:111 - Position obtenue
18:56:35 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 12 satellites
19:01:27 INFO  GpsLoggingService.startGpsManager:563 - Requesting GPS location updates
19:01:27 DEBUG GpsSimpleViewFragment.onWaitingForLocation:474 - true
19:01:28 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 0 satellites
19:01:29 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 3 satellites
19:01:30 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 5 satellites
19:01:31 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 6 satellites
19:01:32 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 8 satellites
19:01:33 DEBUG GpsLoggingService.onLocationChanged:732 - Has description? false, Single point? false, Last timestamp: 1465491395361
19:01:33 WARN  GpsLoggingService.onLocationChanged:780 - Only accuracy of 128.0 m. Point discarded.Point inexacte ignoré
19:01:33 INFO  GeneralLocationListener.onStatusChanged:102 - gps is temporarily unavailable
19:01:33 DEBUG GpsLoggingService.stopGpsManager:635 - Removing towerLocationManager updates
19:01:33 DEBUG GpsLoggingService.stopGpsManager:640 - Removing gpsLocationManager updates
19:01:33 DEBUG GpsSimpleViewFragment.onWaitingForLocation:474 - false
19:01:33 DEBUG GpsLoggingService.setAlarmForNextPoint:912 - Set alarm for 120 seconds
19:01:33 DEBUG GeneralLocationListener.onGpsStatusChanged:111 - Position obtenue
19:01:33 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 9 satellites
19:06:26 INFO  GpsLoggingService.startGpsManager:563 - Requesting GPS location updates
19:06:26 DEBUG GpsSimpleViewFragment.onWaitingForLocation:474 - true
19:06:26 INFO  GeneralLocationListener.onGpsStatusChanged:137 - GPS a démarré, en attente de la position
19:06:27 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 0 satellites
19:06:28 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 1 satellites
19:06:28 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 5 satellites
19:06:29 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 5 satellites
19:06:30 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 5 satellites
19:06:31 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 7 satellites
19:06:32 DEBUG GpsLoggingService.onLocationChanged:732 - Has description? false, Single point? false, Last timestamp: 1465491395361
19:06:32 WARN  GpsLoggingService.onLocationChanged:786 - Only accuracy of 48.0 m and timeout reached.Point inexacte ignoré
19:06:32 DEBUG GpsLoggingService.stopGpsManager:635 - Removing towerLocationManager updates
19:06:32 DEBUG GpsLoggingService.stopGpsManager:640 - Removing gpsLocationManager updates
19:06:32 DEBUG GpsSimpleViewFragment.onWaitingForLocation:474 - false
19:06:32 DEBUG GpsLoggingService.setAlarmForNextPoint:912 - Set alarm for 120 seconds
19:06:32 DEBUG GeneralLocationListener.onGpsStatusChanged:111 - Position obtenue
19:06:32 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 8 satellites
19:07:19 DEBUG GpsMainActivity.populateProfilesList:545 - Current profile:Profil par défault
19:07:19 DEBUG GpsMainActivity$14.onServiceConnected:1082 - Connected to GPSLoggingService from MainActivity
19:11:27 INFO  GpsLoggingService.startGpsManager:563 - Requesting GPS location updates
19:11:27 DEBUG GpsSimpleViewFragment.onWaitingForLocation:474 - true
19:11:28 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 0 satellites
19:11:28 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 1 satellites
19:11:28 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 8 satellites
19:11:30 DEBUG GpsLoggingService.onLocationChanged:732 - Has description? false, Single point? false, Last timestamp: 1465491395361
19:11:30 WARN  GpsLoggingService.onLocationChanged:780 - Only accuracy of 48.0 m. Point discarded.Point inexacte ignoré
19:11:30 INFO  GeneralLocationListener.onStatusChanged:102 - gps is temporarily unavailable
19:11:30 DEBUG GpsLoggingService.stopGpsManager:635 - Removing towerLocationManager updates
19:11:30 DEBUG GpsLoggingService.stopGpsManager:640 - Removing gpsLocationManager updates
19:11:30 DEBUG GpsSimpleViewFragment.onWaitingForLocation:474 - false
19:11:30 DEBUG GpsLoggingService.setAlarmForNextPoint:912 - Set alarm for 120 seconds
19:11:30 DEBUG GeneralLocationListener.onGpsStatusChanged:111 - Position obtenue
19:11:30 DEBUG GeneralLocationListener.onGpsStatusChanged:132 - 10 satellites
....

**Comment by matthewwhall** [comment]
I am seeing a similar issue on a Galaxy S7.

 Note to developers; try installing another GPS app, such as maverick from codesector. I suspect that when you use maverick to view a map (and to find your location) then gpslogger is somehow interrupted. On a day when I use maverick, gpslogger records only a few points, with large gaps in the record. On days when I don't use maverick, it works fine. This makes it useless, since the log from a maverick day is more interesting.

**Comment by mendhak** [comment]
A few things to try - try to update AGPS data with [GPS Toolbox](https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2&hl=en_GB) - get it to download the data then try GPS again.

I noticed from the logs that it's not reaching an accurate point, even after repeated attempts.  You can also try increasing the accuracy interval to a larger value.  

The Maverick + GPSLogger issue may be different, I'm trying it right now and it seems fine, no gaps.  What providers are enabled in maverick, fused/network - vs what providers in GPSLogger, gps/network/passive ?

**Comment by Alberto2712** [comment]
Hi,
I ve already done AGPS updates and set accuracy interval to 300. And still recording less than 1 point on 10 (interval set too 120s for example).
If I choose the option keep gps on between points or if I start another GPS app beside then all points are correctly recorded.

When I see log file, it seems than it tries to fix a point but stops very fast even if there is no fix (and it doesnt wait for the acuracy interval). I ve reinitialize the app, reinstaled it, ... and still not recording all points.

Regards,
Adrien

**Comment by DracoriusRhonix** [comment]
Wanted to mention here that i am having a similar issue as Alberto2712. A lot of points get discarted with the "gps is temporarily unavailable" appearing a lot in the log. 

Log extract:
`19:47:31 INFO  GpsLoggingService.startGpsManager:563 - Requesting GPS location updates
19:47:31 INFO  GpsLoggingService.startGpsManager:574 - Requesting cell and wifi location updates
19:47:31 DEBUG GpsSimpleViewFragment.onWaitingForLocation:473 - true
19:47:31 INFO  GeneralLocationListener.onGpsStatusChanged:143 - GPS started, waiting for fix
19:47:32 DEBUG GpsLoggingService.onLocationChanged:741 - Has description? false, Single point? false, Last timestamp: 1491241355978
19:47:33 DEBUG GeneralLocationListener.onGpsStatusChanged:138 - 25 satellites
19:47:33 DEBUG GeneralLocationListener.onGpsStatusChanged:138 - 24 satellites
19:47:33 DEBUG GpsLoggingService.onLocationChanged:741 - Has description? false, Single point? false, Last timestamp: 1491241355978
19:47:33 INFO  GeneralLocationListener.onStatusChanged:108 - gps is temporarily unavailable
19:47:33 DEBUG GpsLoggingService.stopGpsManager:635 - Removing towerLocationManager updates
19:47:33 DEBUG GpsLoggingService.stopGpsManager:640 - Removing gpsLocationManager updates
19:47:33 DEBUG GpsSimpleViewFragment.onWaitingForLocation:473 - false
19:47:33 DEBUG GpsLoggingService.setAlarmForNextPoint:913 - Set alarm for 300 seconds
19:47:33 DEBUG GeneralLocationListener.onGpsStatusChanged:117 - Fix obtained`

As you can see it has about 2 seconds to try to get a lock before the sampling of the point is terminated due to the "gps is temporarily unavailable" event. I have "Duration to match accuracy" set to 60 seconds, and "Absolute time to GPS fix" to 120 seconds. So two seconds seems to be awfully short.

This was tested on a Huawei Nova (android 6.0), with the app set as protected and I also set to app as 'allowed' in the ignore optimizations list to try to make the OS behave as nice as possible.

Let me know if there is something i could try that could give some more insight into the issue.

Kind regards,
Dracorius

**Comment by sookoll** [comment]
I have different issue with Huawei P20 Pro. I have same settings as my previous phone (Sony Z1 Compact) - Keep gps on between points, Most often logging. But app logs only these points, when I unlock my phone. 0 logged point when phone is locked. Which is frustrating.

**Comment by snoir** [comment]
Same problem here with the Huawei Y6 2019, Android 9 and Emui 9.1
I've tried to disable every optimization but the app log only when I unlock the phone

**Comment by sookoll** [comment]
> Same problem here with the Huawei Y6 2019, Android 9 and Emui 9.1
> I've tried to disable every optimization but the app log only when I unlock the phone

Hi, I have found solution, that works for me. Besides battery optimization, there is also list of apps, that  phone have rights to manage. I disable that for gpslogger. After that it complain about big battery usage for this app, but it works correctly.

**Comment by mendhak** [comment]
I think what you say matches up with:  https://dontkillmyapp.com/huawei?app=GPSLogger

(I've added a link to it in the FAQ)

**Comment by sookoll** [comment]
Yeah, pretty much. But I'm quite sure that I didn't change half of the settings mentioned there.

**Comment by snoir** [comment]
It is working now, I already had disabled the manage permission for the app. The missing thing was to put the power plan to performance. Thanks !
