### ISSUE TITLE
Amend csv format to include HDOP, VDOP, PDOP and geoid height

### ISSUE THREAD

**Issue by bjohas** [mendhak/gpslogger#449]
It would be good to have one complete output format, that contains all data captured from the GPS receiver.  I suggest adding HDOP, VDOP, PDOP and geoid height to the CSV file.

**Comment by mendhak** [comment]
In case you want to try it out now (since I don't know when I can release it)

[Updated APK](https://dl.dropboxusercontent.com/u/51905631/gpslogger-78-csvmore.apk) ([signed](https://dl.dropboxusercontent.com/u/51905631/gpslogger-78-csvmore.apk.asc),[hashed](https://dl.dropboxusercontent.com/u/51905631/gpslogger-78-csvmore.apk.SHA256))

**Comment by bjohas** [comment]
I've tried this - thanks! Seems to work fine, apart from the fact that ageofdgpsdata and dgpsid seem to be empty. I'll try again logging a long path, to see whether that makes a difference.

**Comment by mendhak** [comment]
Yep that sounds moral,  they won't always be populated, only when available
and provided.

**Comment by mendhak** [comment]
v79 released to market

**Comment by bjohas** [comment]
Many thanks! Great that this is in the released version now!
