### ISSUE TITLE
addapt logging time to speed

### ISSUE THREAD

**Issue by jlmalet** [mendhak/gpslogger#454]
hello
imagine I'm doing some backcountry ski... when I climb I usually do a 2-5km/h, when I go down I do about 30km/h
when I go up, I can log each point at 15s interval
when I go down, I should log each point at 1s interval

the idea is to addapt the interval regarding the speed.... let say I want a distance between point of 10m, at 2km/h I have to wake the gps each 18s (10m*3600s/2000m) but at descent, I have to wake up the device each 1.2s

thanks and regards

**Comment by mendhak** [comment]
This is a  catch 22 - in order to increase logging frequency it needs to know the speed; in order to know the speed it needs to log frequently.  The only way to do this is to set the interval to 1s for the entire way.  The only other way to do it would be to have it logging at 1s behind the scenes constantly with a wakelock, which will drain the battery quickly.

**Comment by jlmalet** [comment]
well quite not...
look at the following example :
logging each 60s
distance between log1 and log2 = 100m
=> speed 100m/60s > max speed
=> new interval 30s
distance between log2 and log3 = 60m
=> speed 60m/30s > max speed
=> new interval 15s
distance between log 3 and log 4 = 10m
=> speed 10m/15s < max speed
=> new interval 30s

and so on.... of course interval step can be fixed (here i took a 1/2
factor scale but it could have be 60 50 40 30 20 10, or something else...)
(better if user configurable)
