### ISSUE TITLE
Password setting

### ISSUE THREAD

**Issue by marcoas** [mendhak/gpslogger#459]
only have access to change (or see ) configurations , with a password.
It is useful so that no one can change the configuration parameters

**Comment by mendhak** [comment]
Enforcing password protection on these config files is quite difficult because they are meant to be hand crafted if necessary, and any password protection would require encrypting - in other words, this is too niche.  

Instead I'd suggest having a look a separated out solution like [AppLock](https://play.google.com/store/apps/details?id=com.domobile.applock&hl=en_GB).

**Comment by marcoas** [comment]
OK. Look for it
