### ISSUE TITLE
Change profile while logging doesn't take effect

### ISSUE THREAD

**Issue by bjohas** [mendhak/gpslogger#469]
- Start logging in one profile
- Change profile
- Logging continues in previous profile, but:
- Number of points counter does not update (see https://github.com/mendhak/gpslogger/issues/468)
- "Log view" shows points recorded correctly.

When logging is stopped, and restarted, the new profile takes effect.

**Comment by mendhak** [comment]
Yep this is pretty much same as http://code.mendhak.com/gpslogger/#ivechangedthesettingsbutitsstillshowingusingtheoldsettings since the profiles are nothing but a collection of settings - those new settings won't take effect till stopping and restarting logging, *or* the next point is logged.  Forcing a stop and start would be too complicated, since it would require bypassing user settings which brings its own support issues.
