### ISSUE TITLE
error: illegal escape character  in BuildConfig.java file 

### ISSUE THREAD

**Issue by silhan52** [mendhak/gpslogger#477]
Hi,
I Clone the project using Android studio 2.2.2 on windows, when I run the project there is an error 

> illegal escape character on the BuildConfing.java file 

 public static final String[] TRANSLATION_ARRAY = new String[]{"G:\Developer\AndroidStudioProjects\gpslogger\gpslogger\src\main\res\values","G:\Developer.......,....,....};

BuildConfig.java  is an Auto generated file and should not be edited.

**Comment by mendhak** [comment]
I see the problem now. `TRANSLATION_ARRAY` is a build constant being generated based on the existence of translation directories.  The problem is [here](https://github.com/mendhak/gpslogger/blob/master/gpslogger/build.gradle#L279) in which the path was being split by `/`, but of course Windows will use `\`, and the compiler in turn is wondering what those weird escape characters are now.  I've changed this now to use `File.separator` so that should work.  Reclone
