### ISSUE TITLE
Allow configurable max speed

### ISSUE THREAD

**Issue by edwardmuel** [mendhak/gpslogger#489]
https://github.com/mendhak/gpslogger/commit/d2e7ef1261edb9f2881c8f02912ff40cc24d24d0#diff-4be86eada42fe15ff94ce2f44a03f9e1R779

This breaks some use cases such as riding as a passenger on an airliner.
Max acceptable speed needs to be configurable with a way to set a specific/unlimited max speed.
I had to downgrade to v80.

**Comment by mendhak** [comment]
What were you using to record above 600km/h - I had thought that phones can't record GPS at those speeds.

**Comment by edwardmuel** [comment]
A Galaxy Grand Prime. The reported speeds reported in the logs are all far too low (even for normal driving), but I'm guessing my phone's sensors aren't very trustworthy. On one of the flights the speed was reported as mostly around 0.
I guess your check calculates speed based on previous coordinates+timestamp.

**Comment by tneu33** [comment]
I also vote for a configurable max speed - if that low max speed limit is necessary in some cases.
I've previously logged some paths of my travel, part of which contains flights. Today I was wondering why the logging seemed to stop soon after the takeoff. Then I found in the log view that the points were discarded due to too big distance jumps per timestep. Logging resumed just before landing when speed decreased
Previously I've used Galaxy S5, today I used Galaxy S7 Duos. Both of them work reasonably well in those speeds, though the speed readings look a little bit low. Basically, commercial airliners fly aroung 900 km/h air speed, and tail wind may further increase the ground speed by another 100 km/h. So it should be possible to set the limit to at least 1000 km/h, preferably a little bit higher.

**Comment by mendhak** [comment]
I'm going to up the max speed to 1285 km/h.  The reason for not making it a configurable value is - this is added to detect GPS jumps so the algorithm itself may change soon or max-speed detection may just go away.  So I don't want to make this look like a feature.

**Comment by mendhak** [comment]
v83 released to market.
