### ISSUE TITLE
How to get data over HTTP with PHP on my server?

### ISSUE THREAD

**Issue by andreabazerla** [mendhak/gpslogger#492]
I need help, please! I'm very confused.

How I can print on my server at address **.../.../test.php** data as **?lat=%LAT&lon=%LON** with custom URL modality over HTTP with PHP?

(I will offer you a coffee, your app is great!)

Thanks!

**Comment by mendhak** [comment]
OK I haven't touched PHP in a long time but let me try to answer...

In CustomURL settings - `http://yourserver/test.php?lat=%LAT&lon=%lon`

In your PHP page, something like

    <?php
        echo $_GET['lat']; 
        echo $_GET['lon'];
    ?>

Of course from there you'll need to write it to your file or database, the `echo` just prints it to screen and nobody will see that.

**Comment by andreabazerla** [comment]
Yep, it's right but it doesn't work!
Where am I doing wrong?

**GPSLogger for Android**
```
http://.../test.php?lat=%LAT
```   

**test.php**
```php
<?php

    if (isset($_GET["lat"])) {
        echo $_GET["lat"];
    } else {
        echo "ERROR";
    }

?>
```   

**http://.../test.php**
```
ERROR
```

**Comment by mendhak** [comment]
Wait - are you hitting the page directly in your own browser?  You won't see anything that way because there's no querystring variables being sent. To see it working in your own browser, go

    http://.../test.php?lat=1111&lon=2222

GPSLogger will be sending lat/lon to that URL but you won't be able to see that because the values are being echoed back to it, not to yourself.  You'll have to write some code to take those lat/lon values and store them somewhere like a file or a DB.  Then you can test end-to-end.

**Comment by mendhak** [comment]
Try writing from the PHP page to a file

    file_put_contents("lookatthis.txt", $_GET['lat']." ".$_GET['lon'] , FILE_APPEND );

Then hit the page from GPSLogger.  Then look for a `lookatthis.txt` file

**Comment by andreabazerla** [comment]
Oh it's works! I'm too confused.

Why I can't get lat and lon directly in test.php, to save into PHP variable and then to print them?

Thank you, @mendhak!

**Comment by mendhak** [comment]
Web pages are request-response.  When you hit that page it looks at what querystring you sent, prints it to the page and responds with that page back to you.  Similarly when GPSLogger adds its querystring, the response is sent back to GPSLogger.  

So you can definitely save lat/lon to PHP variables, just that you have to also send them in the querystring.  In your example you were hitting test.php but not sending any lat/lon.

If you hit

    http://.../test.php?lat=1&lon=2

You should see it saved to variable then printed out to page

**Comment by andreabazerla** [comment]
So what is the best solution to get lat, lon, etc with your app, in PHP to store them in a MySQL database and to print them in a web page in your opinion? I need some advices about it, because maybe I'm doing it wrong.

**Comment by mendhak** [comment]
You'll need two parts to this.  

The first is a 'receiver.php' page which GPSLogger sends its data to every few minutes or whatever you've configured.  In this page, write the values to a file or database.  

The second is a 'display.php' - when you browse to this page it goes and queries the database or file and displays those values on the page.

If you're going to do a lot of logging, maybe consider a database instead of a file. 

Might be worth mentioning - [export-mike has written an API](https://github.com/mendhak/gpslogger/issues/452) which can look at GPX files uploaded to Dropbox.  So you'd have to enable Dropbox upload and your display page would query the Dropbox API instead.

**Comment by mendhak** [comment]
Hey that's great to know. Future searchers will benefit from this too, so thanks

**Comment by jacknab** [comment]
what is the full url string your using in the custom URL option?
