### ISSUE TITLE
Accuracy in HTTP mode every 0 seconds

### ISSUE THREAD

**Issue by andreabazerla** [mendhak/gpslogger#494]
Hi, I've tested the accuracy of your app in HTTP mode every 0 second.

In this map of Verona (Italy), that I've created, there are all highways and I've mapped all movements with my car, but the accuracy isn't so high.

(I've setted "High accuracy" about GPS on my Nexus 5X)

![Verona](https://s28.postimg.org/9e3wgmg4t/Cattura.png)

What is the problem? There is a solution?

In this second image, for example, I was stationary for some minutes at a traffic signal ([45.431241,10.983451](https://goo.gl/maps/8y9YxX6H2S72)), but there is some points out from highway's line.

![Intersection](https://s28.postimg.org/suom35b8t/Cattur2a.png)

**Comment by mendhak** [comment]
GPS drifts when stationary - this is normal.  Usually this happens because the receiver is receiving multiple paths of signals due to environment.  

Solutions are - you can add a distance filter, so a minimum distance required between previous and current point.  Or you can enable activity recognition option so that it doesn't log when there is no movement.  That's based on the phone's activity recognition provided by accelerometer, it recognizes states like 'tilting', 'still', 'in vehicle', on foot' etc

**Comment by mendhak** [comment]
I've added a FAQ item for this - http://code.mendhak.com/gpslogger/#whydoesgpsdriftwheniamstationary

Should have done it earlier as this is a common question
