### ISSUE TITLE
Feture Request:  DGPS

### ISSUE THREAD

**Issue by Hans3702** [mendhak/gpslogger#505]
**Differencing GPS** 
By place an old phone at home with an app, enter the exact location or average location and let the  "_on the road_" app connect by file exchange ( eg FTP) or a utp/tcp connect and make that one very accurate.  (only for GPS location)

**Comment by Fi156** [comment]
For that you will need RAW GNSS measurements.
Further reading on that topic:
http://gpsworld.com/google-opens-up-gnss-pseudoranges/

With external GNSS Chips and Antennas:
https://play.google.com/store/apps/details?id=gpsplus.rtkgps&hl=de
http://www.rtklib.com/

**Comment by mendhak** [comment]
I've spent the past few days trying to read up on this and understand more about GNSS and the new Android 7 APIs.  It's not easy, a lot of TLAs and 'tribal' knowledge floating about so it took a while to even scratch the surface!

From what I'm seeing, the GNSS API is a way to get at the raw data that the OS/chip normally has access to and uses to calculate locations.  

And for DGPS, I think two devices - one fixed, one moving - will need to be recording this GNSS data and sending to a single location for comparison or processing.

This really isn't what GPSLogger is meant for, it's to be simple and just logs the location.  I speculate it would also require wakelocks because of the Android [duty cycle](https://www.blackdotgnss.com/2016/09/20/ppp-with-smartphones-are-we-there-yet/) that needs to be bypassed.  But wakelocks are always something I push back against as this goes against the battery saving design.  Even without  the wakelock, this doesn't feel like something GPSLogger should be doing, rather it should be in its own dedicated app.  I did find a [GNSS app](https://github.com/google/gps-measurement-tools) by google but not sure what it's recording. 


As this is a new area of knowledge for me let me know if any statements here are incorrect.

**Comment by Hans3702** [comment]
youre are right:  "This really isn't what GPSLogger is meant for"  
I was just thinking of  put a device ( old phone)  on a know point and  communicate with the mobile set nearby what diff between the real location and the gps location is, at a given time
assuming that the "fault" wil beethe same on the mobile set if it is near by 
sometimes I found a 5 meter dif a problem with photo geotags :-)  

I will try to make a setup with two phines ans macrodroid or tasker :-)  just for fun
