### ISSUE TITLE
pre-defining preference name values before apk build

### ISSUE THREAD

**Issue by jacknab** [mendhak/gpslogger#511]
Hello,

Could I change the PreferenceName values in this file listed below, before I build the apk.  So when the apk is installed on a device what ever I changed would be set inside the app.  Example:  opengts settings *(in the /path setting I would like to place the prams that are passed through my api url I made for saving the lat & lng to database.   
/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/common/PreferenceNames.java

**Comment by mendhak** [comment]
The `PreferenceNames.java` file is just the key, not the value itself.

If I am understanding correctly, you'd like to predefine the *values* themselves?  In other words, you want to compile it so that your OpenGTS server is already pointing at `example.com`

Taking OpenGTS Server as an example, you can return a default value here:
https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/common/PreferenceHelper.java#L754-L757

That should usually be enough to predefine your values.  If for some reason that doesn't work, you may also need to return a `defaultValue` from the preferences here:

https://github.com/mendhak/gpslogger/blob/06aa096b525f00f12d078ba41707620684e2a6fc/gpslogger/src/main/res/xml/opengtssettings.xml#L13
