### ISSUE TITLE
Big intervals without points data

### ISSUE THREAD

**Issue by uzazzap** [mendhak/gpslogger#540]
Hi!
I have tablet Lenovo Tab 3 Plus TB7703X and i have next trouble: my tracks every day have few issues, when logger make 2-4 hrs parking, but tablet this time moving in car in city.
I collect debug log, and when my track status is few hrs parking, i see next messagge so many time : DEBUG GeneralLocationListener.onGpsStatusChanged:132
I pin here my debug log, and hope for help to solve this.
And my settings is here:
time_before_logging=20
distance_before_logging=100
accuracy_before_logging=100
retry_time=20
absolute_timeout=60
startonapplaunch=true
startonbootup=true
log_kml=false
log_gpx=false
log_plain_text=true
log_opengts=true
listeners=gps
new_file_creation=custom
new_file_custom_name=00000-%DAY
new_file_custom_keep_changing=trues
new_file_custom_each_time=false
autosend_enabled=true
autosend_frequency_minutes=60
autosend_frequency_whenstoppressed=true
autosend_sendzip=false
autoopengts_enabled=true
opengts_server=example.com
opengts_server_communication_method=http
autoopengts_server_path=/
opengts_device_id=50243
autoftp_server=ftp.example.com
autoftp_port=1234
autoftp_username=uname
autoftp_password=password
autoftp_enabled=true
autoftp_directory=/
[debuglog.txt](https://github.com/mendhak/gpslogger/files/1006173/debuglog.txt)

**Comment by mendhak** [comment]
Initially just 1 satellite, absolute timeout.  Later despite 30 satellites, still no fix.  I am wondering if your issue is actually [here](http://code.mendhak.com/gpslogger/gps-fix-details.html).  

There are two things you can try here. 

First is try to increase the absolute timeout to a higher value - start with 1800, then leave the app running in place.  Let it keep going and going in place till it starts being able to fix on points (filling up the almanac).  

Another thing that could be tried is use [this app](https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2&hl=en_GB) to update the AGPS data - so instead of the GPS chip slowly gathering all the data it needs, you can use an AGPS app to download it manually and apply it.

**Comment by uzazzap** [comment]
now i try set absolute timeout to 1800 and track still have few points and big intervals between that points

**Comment by mendhak** [comment]
Can you try a few other apps - such as [this](https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2&hl=en_GB) or [this](https://play.google.com/store/apps/details?id=com.ilyabogdanovich.geotracker) - do those suffer from similar gaps in logging.  I am wondering if this is a device issue.  For example you could also have a try on another device (if you have an extra) and see if they also suffer when logging.

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
