### ISSUE TITLE
Feature request: Add %START time to Custom URL

### ISSUE THREAD

**Issue by fatcat386** [mendhak/gpslogger#543]
Hello!

I very like your app! I using it for remote logging and live tracking of my MTB routes. I write data incoming from Custom URL to START_TIME_OF_FIRST_REQUEST.csv file on my private server. I must hold the start time in some shared var to append new coordinates to this file (start time pointing to it). If there is gap of 10 min between requests I clear that var and then next data goes to new file. Also I use trick - "*" in annotation to do the same. There is no way (or I did not find it) to tell server that user ends that track.

All it can be simplified. I suggest to add new URL parameter, %START or %START_TIME for example. It must be equal to first request's %TIME all the time transmission lives. Until user press stop and start new track.
And now we have ready mechanism to separate remote tracks without any headache. Just write always to %START.csv and you done!

All this great for logging. Yet it would be very cool to have way to tell server about stop event in separate %STOP (or not %LIVE) for example. It is to end live tracking on map at this moment and place finish flag :3.

Sry if english not well.
Many thanks for your great app!

**Comment by danielfaust** [comment]
Good idea.

**Comment by danielfaust** [comment]
Maybe adding a session-id, which well could be be a unix timestamp of the starting time, would solve this issue. This could also help determine which "run" a datapoint belongs to if one logs into 1 file per day, if it is stored along with the location data.

**Comment by mendhak** [comment]
There is a [session start timestamp](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/common/Session.java#L109) which could be used. It won't match the first point's `%TIME` since the session could start but take a few minutes to get to the actual first point.  However it can be treated as a session ID of sorts.  I'll have a look around it to see that its value doesn't get lost or changed frequently.  I'm hopeful it's good enough, then it's just a matter of adding another param to the custom URL. 

Determining a stop is a different matter.  This requires sending a completely different constructed URL to the endpoint.  It's also subject to the same network mechanisms and retry mechanisms currently in place which means it can also be lost.  I really don't want to get into maintaining an isolated use case like this - at this point it becomes more than a logger, more of a state maintainer.

**Comment by danielfaust** [comment]
I think start events are not needed, since they can be detected if a session-id changes. And for the stop-event it would make more sense to just trigger a http GET event with only a stop message, without any other location data in order to avoid a location lookup. Without mantaining state. Just one attempt to notify the server, best effort, no guarantees. Worst case scenario is that the server will have to fall back to checking if a new session is started while one was active and close it, if so. But it could be nice to have the sever know when logging stops, eventually it wants to do some post processing and this way it can start asap.

**Comment by danielfaust** [comment]
If I'm not mistaken, there is a problem when the service gets killed, because this will call `startLogging()`, which in turn will call `session.setStarted(true)`, which will then generate a new `startTimeStamp`.

I see two ways to handle this:

1) change `setStarted(boolean isStarted)` to `setStarted(boolean isStarted, boolean generateTimeStamp)` and 
`startLogging()` to `startLogging(boolean generateTimeStamp)` and have each invocation specify the gerenation of a new timestamp if required.

2) call `set("startTimeStamp", String.valueOf(0));` when recording stops, and when `setStarted(true)` is called only generate a new timestamp if `Session.getInstance().getStartTimeStamp()` is zero.

**Comment by danielfaust** [comment]
While I have implemented 2), I had second thoughts about the sending of START and STOP events to the server.
The overhead of a HTTP fetch to indicate a start, one to log an annotation, and one to indicate a STOP event doesn't make much sense to me, so there should be a setting in the preferences in order to enable/disable this functionality, which I won't implement.

It only makes sense when recording multiple location points, ie when tracking a bike ride for example.

Also I have been thinking about the session id thing. Maybe it's not a good idea to use the `startTimeStamp` as a session-id, because maybe you want to stop tracking for a couple of minutes for whatever reason, and resume tracking later on, this would result in two session id's where a single one would make more sense.

While I have implemented this session-id stuff now, I'm not sure if it is really that useful.  Maybe another button or menu entry should exist in order to generate a session id explicitly (manually). @fatcat386 what's your opinion on this?

**Comment by mendhak** [comment]
Yes it's correct, if the service is killed and restarted, a new timestamp will be generated.  However I don't want logic catering just for this specific *custom-url-start-after-service-restart* scenario to make its way into the more generic `startLogging` and `setStarted`.  Even GPX gets a new `trk` when the service is restarted.  GPS logging at its core is a series of location events.  What constitutes start and stop may be different for different people, but turning this app iinto that state manager is highly undesirable.  The start time happens to be used internally and I can look to expose it via that parameter.  

But even a simple thing like using timestamp or adding extra buttons for session id instead of a timestamp introduces additional complexities, as you said:

> because maybe you want to stop tracking for a couple of minutes for whatever reason, and resume tracking later on, this would result in two session id's where a single one would make more sense.

Extra logic, extra complexity, extra maintenance just to cater to one specific scenario.  I have similar sentiments around the stop logic - while I understand and it's best effort/best intentions - that usually doesn't fly over time as I am left to deal with issues around this.  Even the more standardized OpenGTS doesn't deal with start/stop indicators and for good reason.  

Leave this one with me I'll start playing with the `%START_TIME` set to an ISO time, but without any `%STOP` parameter.

**Comment by danielfaust** [comment]
What about sending the filename as a session-id? That would make a lot of sense, since on the device it's the filename which is grouping all those events.

**Comment by mendhak** [comment]
Yes that's a good idea.  I've called it straight up filename to avoid ambiguity 

`%filename` and `%starttime` added as custom URL parameters.  

If anyone would like to test you can sideload the APK (you will still receive Play store updates):

[APK](https://drive.google.com/open?id=0B6IOK82n4BkAdVlYUl96eGpVNms), [Signature](https://drive.google.com/open?id=0B6IOK82n4BkAX2hCZHhUd01TemM), [Checksum](https://drive.google.com/open?id=0B6IOK82n4BkAVi1YUTJCbUhZU3M)

`gpg --verify gpslogger-87-issue543.apk.asc`
`sha256sum -c gpslogger-87-issue543.apk.SHA256`

**Comment by danielfaust** [comment]
Yes this is working. Both the comment in CSV and also the two new parameters.

**Comment by fatcat386** [comment]
Hello guys! Thanks for your participation!
It is very useful additions. I trying it.

Yes I understand unreliability of stop event. I can confirm that data requests (one or few) sometimes lost and not received by server. Also data can be out of order so I must sort it by timе before render track. So end event can be received before previous data and things go wrong.

Yet sometimes on long routes and, possible, on use of other apps (camera, google maps etc), app can stop logging and icon of it disappear from top bar. App seems live on enter and is in logging mode, but stat info is not updating so I need to press Stop and Start again. Icon reappears and app start work normally. Doze mode is off. So i think it is android memory things. But now we get another %starttime/%filename and two remote (or local) tracks instead of one. It can be undesirable.

In that conditions idea is born. When user press start, app asks him to continue previous track (yes/no). So if "yes" - %starttime/%filename used from previous track. Or it can be separate button "Continue". We need to keep previous track %starttime/%filename somewhere in app to make that behaviour work.

Cheers!


P.S. I also have another separate idea about adding input field at main screen. User can freely anytime (logging or not) change it. Its value must go to some %custom param every request. There can be a lot of uses for it on remote side. Think it track name, session or something else. So we can tie data by something concrete and independent of glitches and so on :3.

**Comment by danielfaust** [comment]
> P.S. I also have another separate idea about adding input field at main screen. User can freely anytime (logging or not) change it. App must remember it between launches. Its value must go to some %custom param every logging request. There can be a lot of uses for it on remote side. Think it track name, session or something else. So we can tie data by something concrete and independent of glitches and so on. It is for consideration too.

I've added two buttons which insert annotation on a button press ("mark-1" and "mark-2") and find them very useful. I also decreased the size of the lat/long font.

![screenshot_20170528-202346](https://cloud.githubusercontent.com/assets/320098/26531177/f9523cda-43e3-11e7-9ade-e7f73d6fe0cb.png)

These changes lead me to think about creating a new view optimized for bike rides/hikes with extra buttons to mark certain events and also modify the start/stop-button behaviour, because having it stop when accidentally touching it slightly is not ok. Longpress for start/stop.

I also was thinking about having one such a variable which gets stored into the preferences, because this can be very useful (join multiple sessions via that string-variable, use it to label a group of sessions). While @mendhak doesn't like the idea of having something owning state, I believe that such a variable does indeed make a lot of sense. It's a state the user is in, a property of the user, just like his location is a property of him.

**Comment by mendhak** [comment]
The killing and aggressive-pausing of the service is actually going to be occurring a lot more with Android O, I imagine I'll be getting a lot more emails in the coming year around increased disappearing.   Several other logging apps tend to use wakelocks to keep the service alive in the background but that's sacrificing battery life.  I've followed the Android dev guidelines on keeping a service running (make it a background service, display a notification...) but that does mean it can get picked as a candidate to kill.  Just a guess but does it get killed if you set the notification to be visible (versus not visible in the status bar)

Yes as with anything, any additions to the app would probably make sense within a certain context, but not all contexts - I have to balance features between what users consider to be priorities and what works in general for most users.  This means that well intentioned features and requests don't always make it through.

**Comment by fatcat386** [comment]
> I've added two buttons which insert annotation on a button press ("mark-1" and "mark-2") and find them very useful. I also decreased the size of the lat/long font.

Yes, annotation (i mean %desc) can be used to send different signals to server. They can lost, but anyway it is useful i think.

I understand @mendhak about balance and would be discouraged by buttons for truck drivers for example. Although I think we have a lot in common. And such functional can be hidden by default. Again, this is just my thoughs.

> Several other logging apps tend to use wakelocks to keep the service alive in the background but that's sacrificing battery life.

I use 5 sec interval, 5 meters distance, "GPS always on" and "Don't log then im not moving". And have good clear tracks. If I disable "GPS always on" then I have bad tracks. In such usage scenario I can confirm that battery not drain too fast (I use 4050 mAh batt). I used before phone with 2100 mAh and it was good too. So it is enough for bike (have 4 hours rides max). Maybe wakelocks is way to go if making it as selectable option. Anyway android becomes too agressive. It closes even messengers sometimes and im not have notifications from they.

**Comment by fatcat386** [comment]
> I think start events are not needed, since they can be detected if a session-id changes. And for the stop-event it would make more sense to just trigger a http GET event with only a stop message, without any other location data in order to avoid a location lookup. Without mantaining state. Just one attempt to notify the server, best effort, no guarantees. Worst case scenario is that the server will have to fall back to checking if a new session is started while one was active and close it, if so. But it could be nice to have the server know when logging stops, eventually it wants to do some post processing and this way it can start asap.

Absolutely right! I miss that message, sorry) It be reliable in 99% cases. But I thinked in that way: user press "Stop" and app send last coordinates with %DESC="*STOP*" (*LAST*, *EOF*) or it can be separate param %STOP=1 and after that it actually stops, not before. What was plan. For other 1% cases there is timeout check on server.  I think we all be happy and further questions about stop will be stopped :3. Let data to can be lost.

**Comment by mendhak** [comment]
v88 has been released to market.  Closing thread as part of cleanup work.
