### ISSUE TITLE
Annotation and logOnce

### ISSUE THREAD

**Issue by danielfaust** [mendhak/gpslogger#546]
I'm starting to undestand the intention of the app, which differs slightly from what I want to use it for.

I want to use it for tracking my bike rides, with the best possible resolution. When the ride is finished, I want to upload the two files which I recorded onto my server. I am recording the csv and kml formats; csv contains a ton of data, perfect for postprocessing with a Python script, for example, and the kml is great for dropping it into Google Earth and eventually for importing it to Google Maps.

MyTracks had this feature of adding a waypoints, which I used to mark certain locations in order to be able to later compute the time differences. I also used joaomgcd's AutoLocation with Tasker to send me an email when a geofence got entered.

So I've been reading the code and now understand how the Annotation works, as well what the "1" button means (had no idea what it does until I checked the logOnce() method)

So the "1" button logs one single point into the file, or creates a new one if a "matching one" does not exist, it only is usable when no logging is active, I don't know what the logic is behind this. If the app is currently not logging, it is clickable and enables logging for that one shot and disables it again. This makes sense when you have the app like a companion where you are not really tracking the path, but just want to gps-log certain events that happen in the day. Which means that they usually would land in that one-file-per-day file. Nice idea. The same goes for annotations, which apparently are "1"'s with added text, but can also be added while logging is active, which is great, but not really useful if you want to add "I'm over the bridge now" while biking at full speed. Here a button logging a "mark-1" is more useful.

But I have my problems with annotations: They don't end up in the csv file also not in the nmea (that's ok), and they overwrite the last added annotation in the kml file. Only the gpx file stores all the annotations as they are entered.

So I need to store three files in order to cover all the data. kml in order to quickly view the data in GE, csv for post-processing and gpx for annotations.

Now, the thing is that I'm adding two new buttons to the screen, which will allow me to set waypoints like I was able to do with My Tracks. So this would basically trigger an annotation with a text like "mark-1" for the left button and "mark-2" for the right button. 

What I want to do now is to store them into the csv and the kml file, so I'll be working on extending the writers for this file. I'm planning to add a new column to the csv file after the "battery", which is "annotation" and will contain the annotation string "jsonified" in quotes (python equivalent would be str('"'+json.dumps(string)+'"')) in order to avoid unicode issues. With kml I guess it should be no issue since it is a more flexible format, so that they can be inserted as placemarks without affecting parseability.

Do you have any thoughts on this? Are annotations the proper way to implement this feature, or should I create something new?

One question about annotations: Do they stack one over the other? For example, if I press the button "mark-1" to create such an annotation 3 times in 1 second, will I get three logged annotations, or will all but the last be discarded until a location fix is obtained? I want to log all button presses.

**Comment by mendhak** [comment]
So I take it you are customizing the code for your personal use?  It does sound like from what you describe - the annotation route is the best way.  That way you can just log to CSV, KML and work from there.  Alternate to CSV is you could also send via Custom URL, have a listener on your server which receives each line (including annotation) and stores it to file/DB, then process from there.  Custom URL stores up the sending if a data connection isn't available so it should work as well; on the other hand CSV is a file on disk so it's safer.

The annotations don't stack, one annotation is 'the only' annotation until it's written. It's then cleared and you can annotate again.  If you wanted to make it a queue of annotations you'd probably have to look at making `Session.setDescription` add to a list instead of overwrite a value, and write all of it out at the next coordinate-point write; you might have to write the same point three times OR just combine them into one string.
