### ISSUE TITLE
'No log if not moving' lags behind on Android 7

### ISSUE THREAD

**Issue by joriswu** [mendhak/gpslogger#570]
When logging at high resolution - keeping GPS on between fixes and log interval 0 - gives fine results, and a Moto G4 happens to still have decent battery life with this. This is what I use for long hikes, and Strava results like total distance and elevation tend to be accurate only with this kind of settings. To avoid a cluttery track during rest breaks, the 'do not log if not moving' option would be useful, yet appears to lag behind the actual movement for about half a minute. It keeps logging the first half minute being stationary, and starts about half a minute after starting to move. The latter makes the otherwise highly accurate track missing about 30 points.

Doze mode has been switched off.

**Comment by mendhak** [comment]
You'll probably want to enable the debug logging option (in general settings) for this to see what's actually going on.  

The logic is - when the OS reports that the phone is still, it will log [once more](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L1073-L1078), then on the next activity update it will [discard the point](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L769) due to the user being still for the past interval.  

So you should see the activity name and any messages around it in the debug log.  It's entirely possible as well that the OS chooses to not report any activity state to the app for a self-determined period of time.  

You can paste the log here as well as email it to gpslogger at mendhak.com

**Comment by joriswu** [comment]
I see logged 'Received location but the user hasn't moved, ignoring' at times were I am definitely moving. So it looks like the OS lags behind considerably in reporting this. Also at the start, it keeps logging without movement for about 30 seconds.

FYI: logging interval set to 0, keep GPS on between fixes.

[gpslogger-debuglog.txt](https://github.com/mendhak/gpslogger/files/1185407/gpslogger-debuglog.txt)

**Comment by mendhak** [comment]
So I had a look at this and I think it's down to the OS reports; when the OS does have a DetectedActivity of type STILL it does stop logging, otherwise continues logging, which is fine.  I can't explain why the OS might say you're still when you're walking.  I also see 

    DetectedActivity [type=IN_VEHICLE, confidence=100]

Which is definitely strange, considering you only recorded for less than 5 minutes (unless you really were... here IN_VEHICLE doesn't count as being still, so logging will continue).  I'm using [this method](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionResult.html#getMostProbableActivity\(\)) so there isn't much I can do here.
