### ISSUE TITLE
GPX file invalid xml

### ISSUE THREAD

**Issue by ksmith97** [mendhak/gpslogger#581]
Some of the GPX files I produced by the application didn't properly terminate.   The last line in the file is as follows
`<trkpt lat="39.643114`

which is obviously invalid. What is more curious is that of the three files I have produced so far two of them are invalid and one is valid.

This is with version 88 and all default settings except for bumping the polling up to 15 seconds.

**Comment by mendhak** [comment]
How did you grab the file, was it off usb, or upload to another location
first. You can usually see incomplete files when copying off usb due to
media scanner

**Comment by ksmith97** [comment]
hmm okay. I did copy them across usb. I have never had problems with that mode before.

**Comment by mendhak** [comment]
It's an issue usually with mtp, I've seen it since the first android phones
till present. Have a look at
https://android.stackexchange.com/questions/46315/not-all-files-are-visible-over-mtp

You can also try regular file transfer if your phone allows alternative
protocols when connecting.

Or the SD scanner app. It forces a rescan and the file appears properly.
Another way to get it to appear is a reboot. But that's a sledgehammer.

In the app I am invoking a media scan after each file sure but the os may
choose to ignore.

**Comment by ksmith97** [comment]
The SO article you linked is specifically about files being "invisible" not about them being copied improperly though. I am actually using the Transfer Files option. I have copied several files including video and have never had an issue with fails being partially copied. I guess I can try to find an on phone text viewer to verify.

**Comment by ksmith97** [comment]
Well that is strange. I was able to view the files on device and you were correct, they are complete. Very strange that copying an xml file has issues but copying others does not. Ah well, better that its not a bug I suppose! Thanks!

**Comment by mendhak** [comment]
Yes, it's the same issue - MTP caching - the file listing will be incomplete, the file itself will be incomplete.  The file is definitely there on disk, you just can't see them over USB.  

You are likely seeing this with GPSLogger because the app is writing to the file more frequently than other apps.  The other apps which downloaded or created those files will have MediaScanner invoked once, which is fine.

**Comment by ksmith97** [comment]
Have you considered making the file write a single write action upon completion of the tracking instead of continuously writing to the file?  I'm not entirely certain of the use case of doing continuous writes, so this is just me spitballing.

**Comment by mendhak** [comment]
Since the tracks can go on for days they would be held in memory and since Android kills services which are especially memory hungry,  the log points do need to be persisted else there will be data loss.  The alternative becomes database storage however that's just a long winded solution to a separate problem - the file itself is not in an invalid state, the protocol _presenting_ the file to you makes it appear invalid; the OS has to perform a media (storage) scan every once in a while which is why [apps like this](https://play.google.com/store/apps/details?id=com.gmail.jerickson314.sdscanner&hl=en_GB) exist. 

The [media scanner](https://github.com/mendhak/gpslogger/blob/5b87b37d1ec13a39f4a73f53cba2c2a1ae4888c1/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/Files.java#L72-L77) is implemented as Android docs have recommended but beyond that YMMV.
