### ISSUE TITLE
Traccar upload option

### ISSUE THREAD

**Issue by andreapx** [mendhak/gpslogger#600]
Hi all,
are you planning to add Traccar upload feature?
THANKS!!!

**Comment by mendhak** [comment]
Hi, hadn't heard of Traccar before this.  It appears to be a more modern OpenGTS?  

I had a look through the [API docs](https://www.traccar.org/api-reference/) - but I am not sure which of the endpoints does the actual location update.  One good thing is it takes basic auth, so potentially (if there's a single endpoint to hit) this can be done off the Custom URL logger.

**Comment by andreapx** [comment]
Yes, it can be done with the "Custom URL logger", but with that option, there is no auto upload and no continuous tracking

**Comment by mendhak** [comment]
You should have almost-continuous tracking, since the app will queue up HTTP requests if data is unavailable.  

I didn't get very with the investigation - although there are demo servers to try against, none of them seem to have the `/api` URL available.

If you do have a server and are willing to tinker, then I've been working on making the Custom URL screen more flexible by allowing custom methods and headers and body.  See the APK posted here: 

https://github.com/mendhak/gpslogger/issues/377#issuecomment-352274833

**Comment by andreapx** [comment]
I had a problem with the traccar server, that's why I didn't have continuous tracking.
The servers are working. The URL is this:
http://demo5.traccar.org:5055/?id=DEVICE_ID&LAT=%lad&lon=%lon&time=%time&speed=%SPD&altitude=%ALT&hdop=1 (I don't know what this last field is!)
Does the custom url server upload with the interval specified in the option?

**Comment by mendhak** [comment]
The Custom URL logging - it'll send the URL as soon as it gets a new GPS point.  And it'll follow the time interval specified.  So think of it as the same as writing to GPX file, but instead of writing to file it'll make an HTTP request.  If you set the logging interval to get a point every 30 seconds, then that will mean every 30 seconds another HTTP request will be sent to your Traccar server.

I tried it in Custom URL logger and this worked for me

    http://demo5.traccar.org:5055/?id=myid&lat=%LAT&lon=%LON&timestamp=%TIME&speed=%SPD&hdop=1

If you need to add your username password, put it next to the domain like

    http://username:password@demo5.traccar.org:5055/?id=myid&lat=%LAT&lon=%LON&timestamp=%TIME&speed=%SPD&hdop=1

The docs led me down a completely different path with the `/api`.  That's really annoying!

**Comment by andreapx** [comment]
> The docs led me down a completely different path with the /api. That's really annoying!

Yes, that has been reeeeeally annoying. I've spent a lot of time troubleshooting it!
Are there other fields that we can send? What is the"hdop" field?
Thanks!

**Comment by mendhak** [comment]
HDOP is [Horizontal Dilution of Precision](https://en.wikipedia.org/wiki/Dilution_of_precision_\(navigation\)) - and I am recording it as part of the [location object](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GeneralLocationListener.java#L60).  I think it can be made available to the Custom URL logger.

**Comment by andreapx** [comment]
You can leave it empty, in fact you can use whatever field you want, no mandatory fields

**Comment by mendhak** [comment]
OK in that case unless an urgent need, the URL above should work for you.  I'll leave it there unless there's big demand for *DOP fields.

**Comment by andreapx** [comment]
Yes yes!

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
