### ISSUE TITLE
Display synchronization information (custom URL and OpenGTS)

### ISSUE THREAD

**Issue by eneiluj** [mendhak/gpslogger#603]
Don't you think it would be interesting to see how many jobs are waiting for network connectivity to send data to custom URL server or OpenGTS server ?

It could be displayed in the "detailed view" like : 
* custom URL last sync : DATE
* custom URL number of positions queued for sending : NUMBER
* OpenGTS last sync : DATE
* OpenGTS number of positions queued for sending : NUMBER

It would be great to actually know when the network connection was lost and how many points were logged since.

**Comment by mendhak** [comment]
The Job Queue I'm using doesn't allow for querying the queued jobs, since its purpose is to offload this work off the main application anyway.  The last sync date *could* be done but then it's now a matter of tracking each job being submitted which is again not something we should be doing with a job queue.  

I do get a hook when the actual work is being done, so the closest I can get is putting it into the Log View - just logging out the URL being requested.

**Comment by eneiluj** [comment]
Yes, perfect. Thanks a lot. This way we can see when the last position was sent and we already know when was the last recorded position.

**Comment by mendhak** [comment]
v91 is released to market.
