### ISSUE TITLE
What were old settings for custom URL

### ISSUE THREAD

**Issue by keepcarlson** [mendhak/gpslogger#613]
Hi - I started using GPS Logger about a year ago.  Had great success.  Stopped using for awhile due to other things.  Now came back to it and have the upgrade that has additional options under Custom URL specifically HTTP Body, HTTP Headers, and HTTP Method.  Most likely due an issue with my receiving server, but I am no longer receiving data from app.  So I am wondering if you could tell me what these parameters were before they were added as options to change? I.e. has the HTTP Method always been GET?  Has the HTTP Body always been lat=%LAT&lon=%LON?  What was the original HTTP Header and what are options here?
Also, my working URL before was http://domain.name.com:port/...../?lat=%LAT&lon=%LON
Now I see example using http://domain.name.com:port/...../log?lat=%LAT&lon=%LON
(So adding in “log” before query ?).  Is the word “log” important?

Again, problem is most likely with my server but trying to account for all possbilities so I can get this working again.  App being used for research and has been very useful!  Thanks so much for any info you might provide.

**Comment by mendhak** [comment]
Hi yes, I [remember you from last time 😁](https://github.com/mendhak/gpslogger/issues/519#issuecomment-282169280).   The settings that you see will have remained unchanged.  I've not added anything that would modify your existing settings either.  

The best way to troubleshoot it would be, 
 
1. Enable your custom URL logging as normal. 
1. Switch to the 'log view' (instead of simple view/detailed view).  
1. Now start logging.  

Now you should see various messages appearing in the log view.  You'll also see a message when the app attempts to send an HTTP request.  You'll also see an error if one occurs, such as unreachable server or 404 returned, etc.  

Alternative - you can just enable debug logging again, grab the debuglog.txt and email it to me `gpslogger@mendhak.com` or attach it to this thread.  Don't email it to github - github ignores attachments.

**Comment by mendhak** [comment]
But to answer your questions, the values you see are the defaults except
for body. Not sure how your body field has been populated, but it won't be
used unless your http method changes from GET to something else

**Comment by mendhak** [comment]
I'm seeing this error. Sorry if bad formatting but the main problem here is that server and port combination is unavailable. 

I tried to check the port as well, there is nothing listening


Error log :

>java.net.ConnectException: Failed to connect to gryffindor.gis.brown.edu/128.148.254.69:6180
	at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:142) ~[na:0.0]
	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111) ~[na:0.0]
	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188) ~[na:0.0


Connectivity check :

    $ nc  -w6 gryffindor.gis.brown.edu:6180       
    nc: can't connect to remote host (128.148.254.69): Connection refused


    $ ping -c 1 gryffindor.gis.brown.edu
    PING pgisarccit1.ad.brown.edu (128.148.254.69) 56(84) bytes of data.

    --- pgisarccit1.ad.brown.edu ping statistics ---
    1 packets transmitted, 0 received, 100% packet loss,     time 0ms


Is this server controlled by someone else, have they turned the listening process off?

**Comment by mendhak** [comment]
I tested again this morning and I can see something has changed, that port 6180 is definitely listening now.  I even sent a test request to it.

I also noticed - the port 6180 does not have an SSL certificate.  I believe it's regular HTTP because you can browse to this direct

http://gryffindor.gis.brown.edu:6180/geoevent

![image](https://user-images.githubusercontent.com/746276/35480882-07874876-0410-11e8-81c1-4975882569fa.png)


So in your case the Custom URL should be over http. I look at your thread from last year and it was regular http:// back then as well, not https.

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
