### ISSUE TITLE
three taps on a version crashes gpslogger

### ISSUE THREAD

**Issue by lvmm** [mendhak/gpslogger#618]
Go to general options, scroll to the end and tap on the version number three times - and it crashes. I found an easter egg? :) GPSLogger 91, Android 6.0.1, Samsung galaxy S5.

**Comment by mendhak** [comment]
You... did find something yes.  😁  Three taps is trying to open the YouTube app, I assume you have that installed by default since it's Samsung?

When you get the crash can you send the crash report.  If there is an option for a message can you indicate LVMM or threetaps, something like that. 

The crash will appear in my Google Developer Console.

**Comment by lvmm** [comment]
Youtube is installed but disabled - why use it at all if I can access youtube in a browser sans ads? But I sent a report.

**Comment by mendhak** [comment]
v92 released to market
