### ISSUE TITLE
SSL issue - hostname not matching certificate subject

### ISSUE THREAD

**Issue by moarf56** [mendhak/gpslogger#627]
Hi,

I use linuxserver/Nextcloud image on an openmediavault docker instance, and I want to use GPSLOGGER with Phonetrack.
My NC have an autoself sign ssl certificat and when I want to send via custom URL I can see in the log GPSlogger can't recognize my server. 

> 18:14:35 DEBUG AppSettings$1.d:91 - adding another consumer
18:14:35 INFO CustomUrlJob.onRun:59 - HTTP Request - https://xxx.xxx.xxx.xxx:9443/index.php/apps/phonetrack/log/gpslogger/82cc9e90739fd4e8414207c5697322a3/s4?lat=xxxx&lon=-xxxx&sat=0&alt=xxx&acc=33.0&timestamp=xxxx&bat=46.0
18:14:35 DEBUG Networks.getKnownServersStore:52 - Getting local truststore - /storage/emulated/0/Android/data/com.mendhak.gpslogger/files/knownservers.bks
18:14:35 DEBUG LocalX509TrustManager.isKnownServer:144 - Checking for certificate - HashCode: 1934130, Subject: CN=*,OU=LSIO Server,O=Linuxserver.io,L=Carlsbad,ST=CA, in keystore: true
18:14:35 ERROR AppSettings$1.e:96 - error while executing job com.mendhak.gpslogger.loggers.customurl.CustomUrlJob@a6d5b4d
javax.net.ssl.SSLPeerUnverifiedException: Hostname xxx.xxx.xxx.xxx not verified:
certificate: sha256/cPj85blG3+WFuZ2KiYTmuLHGPgABxpvvdGGNaImSE3c=
DN: CN=*,OU=LSIO Server,O=Linuxserver.io,L=Carlsbad,ST=CA
``

Nextcloud use 9443 port, and OPENMEDIAVAULT use 443 both ports use ssl with their own cert....
I think GPSLOGGER try to connect directly on xxx.xxx.xxx.xxx:443 not on the good port (xxx.xxx.xxx.xxx:9443) and this is why that doesn't work !

I precised I check the SSl certificat when I enter my URL.

**Comment by mendhak** [comment]
Hi I believe the problem isn't the port, rather it is the verification process.  The certificate itself is accepted however the Common Name does not match the server that you're connecting to - this error gets raised when the actual request is being sent. 

You'll need to generate the certificate and when setting up the Common Name, make it match the server. eg if you connect to example.com make sure your certificate Common Name or Subject Alt Name contains example.com

I am not sure if you removed it in the debug but your certificate has `CN=,` so it's blank.

**Comment by pedalracer** [comment]
I have the same error message with a similar setup.

I use a DSL/Modem/Router (FritzBox AVM in Germany) that creates the self signed SSL cert. At the moment I can not use Let'sEncrpyt with that device :( so I have to use this self signed one.
I copied the cert into Nas4Free that is running on a microserver in my LAN and that Nas4Free is hosting NectCloud. Into that I also copied the cert. 
So, only one cert. I do not know about using exclusively SSL certs for NAS and Nextcloud and perhaps additionally the Router.

The router is set up to portforward port 8080 to the webserver of Nas4Free where Nextcloud runs.
Nextcloud is set to use SSL.

I use a dynamic dns service in order to get access to my webserver anywhere. As things are set up at the moment I can as intended. I can reach my Nextcloud anywhere via smartphone for example. 

My custom url looks like this:
 https://dyn.dns.test.com:8080/index.php/apps/phonetrack/log/gpslogger/82cc9e90739fd4e8414207c5697322a3/testtrack?lat=xxxx&lon=-xxxx&sat=0&alt=xxx&acc=33.0&timestamp=xxxx&bat=46.0

The ssl cert is validated fine afterwards in the the app but I get the error as the threadstarter.

**Comment by mendhak** [comment]
The main issue is around the hostname.  When communicating over HTTPS, clients (such as browsers, libraries) expect the hostname of the target server to match the subject/SAN on the certificate presented.  The SSL validation I'm doing is only to see if the certificate is a trusted one and to trust it.  

What I could possibly do is issue an HTTP GET or HTTP HEAD request against / and throw an error if such a hostname mismatch occurs. When a user clicks validate certificate that extra step is performed. I will play around with this. 

What that will do is warn you that your cert won't work, it won't solve your current issue around dynamic DNS.  

There is another option which is to [start fiddling with the hostname verification](https://developer.android.com/training/articles/security-ssl.html#CommonHostnameProbs) but as the bit says it's a very drastic measure, it's not how SSL should be working.  


For your case you had mentioned you're copying the cert over - why not issue your own cert, with the "dyn.dns.test.com" hostname, but signed by yourself?  That would work.

**Comment by mendhak** [comment]
I've got an APK if you wish to test - the Custom URL screen has an "HTTP Test" item now which will issue a GET request against the URL specified.  The purpose becomes to test connectivity and also to catch issues like hostname mismatches.  So note that this doesn't solve any of your problems, just highlights it earlier.  

[APK](https://drive.google.com/file/d/1K029oyqFNeaw6Isq_C8DAYXGw6dY3v2X/view?usp=sharing),[Signature](https://drive.google.com/file/d/1U5Gi9aN1LxmAp4-C_CZbG1wiZyuUQAOJ/view?usp=sharing), [Checksum](https://drive.google.com/file/d/1wV0PR_wEJS2oOGYgT-1ym5gZJAeg5gnB/view?usp=sharing)

As for creating your own cert, this seems to be a decent guide - https://somoit.net/security/security-create-self-signed-san-certificate-openssl

I am wondering if I should link to this or something similar in the FAQ

**Comment by mendhak** [comment]
v94 released
