### ISSUE TITLE
GPS receiption deactivated before accuracy reached

### ISSUE THREAD

**Issue by jenslauterbach11** [mendhak/gpslogger#630]
Related to Version 92
Mobile Phone: Honor 9, Android 8.0

Accuracy configured to 40m
Time to reach accuracy configured to 60s

Waiting for a good position is already disabled after a few seconds.
In the attached debuglog.txt GPS was disabled already after ~6s.
[debuglog_2.txt](https://github.com/mendhak/gpslogger/files/1786153/debuglog_2.txt)

Regards
Jens Lauterbach

**Comment by mendhak** [comment]
Thanks I'd been meaning to look into this.  

It's due to this check

https://github.com/mendhak/gpslogger/blob/e0f5124adaa0fd4e16edae2b7305bcc978fbb7da/gpslogger/src/main/java/com/mendhak/gpslogger/GeneralLocationListener.java#L108-L111

For whatever reason, the location provider can turn off for a few seconds.  I don't think I should simply stop logging at that point, better to continue waiting instead.  As usual [there is no explanation](https://developer.android.com/reference/android/location/LocationProvider.html#TEMPORARILY_UNAVAILABLE) as to why it happens.

**Comment by mendhak** [comment]
98a5da4750c8247e0c475ac1da2b6837105cdd17

**Comment by mendhak** [comment]
v93 released to market
