### ISSUE TITLE
GPS not disabled after Activity is recognized

### ISSUE THREAD

**Issue by jenslauterbach11** [mendhak/gpslogger#633]
Version 93:

After receiving an update of Activity Recognition it seems that GPS is not disabled until configured minimum interval (here 60s) is passed.
At least the trace "onLocationChanged" is visible each second.
I think this will lead to high battery consumption.

[debuglog-4.txt](https://github.com/mendhak/gpslogger/files/1803802/debuglog-4.txt)

**Comment by mendhak** [comment]
There are a few things going on - the app will attempt to log when the activity recognition determines that the user has been still for too long (get one last point before sleeping) or user has just started/continuing moving again.  In either case it can take a while for a point to be found.  The other bit is the points seen in `onLocationChanged` may either be passive points from other apps if that option is enabled.

**Comment by jenslauterbach11** [comment]
There was no other GPS Receiver App active.

The Trace shows at 17:17:42 that a new position was received.
Because of 

if (!session.hasDescription() && !session.isSinglePointMode() && (currentTimeStamp - session.getLatestTimeStamp()) < (preferenceHelper.getMinimumLoggingInterval() * 1000)) {
            **return;**
} // in onLocationChanged

the processing is stopped (position and quality is not checked!!!) but GPS stays active until minimum interval time is passed. Depending on the configured interval, GPS might stay active for a long time and drains battery.


I would expect that 
- GPS reception is not activated when an Activity Update is received within configured minimum interval or 
- the received point is used (and maybe later dropped due to some filters)  and GPS will get disabled. Maybe some kind of force-flag is needed.

**Comment by mendhak** [comment]
I'm having difficulty understanding the issue here - 

The GPS logging will pause only if the activity detected is `STILL` - the other activities count as movement.  So you should continue seeing points.  In your log file above, your activities are `TILTING` and `IN_VEHICLE` - so logging continues.  The 'idle' timer only occurs when you see `STILL` occur simultaneously.  Exiting the still state will cause logging to continue, and entering the still state will get logging to get 'one last point'.  

The bit of code you've mentioned - that's not related to activity recognition, it's for filtering.  The code for that is:  

https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L1059
