### ISSUE TITLE
Why is altitude usually zero?

### ISSUE THREAD

**Issue by sengsational** [mendhak/gpslogger#658]
This is probably not an issue with the program, but more a point of setting expectations.  If the accuracy is within 20 meters, it would seem that would be sufficient to generate some kind of altitude, but I rarely see anything but zero.  Is this a function of GPS technology or how this program works?

(tried to set this to "discussion", but not sure I have that capability)

**Comment by mendhak** [comment]
If you're not seeing altitude then normally that means the fix was obtained from network (cellular) rather than satellite.  Network based locations tend to have just the lat-long, some accuracy, but not always an altitude.  

It is also possible to get zero altitude on GPS based locations - but that's specific to the phone.  If you want an altitude in the GPS logs, under the listeners, only enable satellite locations.  It'll take longer to get a fix but you should then always have an altitude.

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
