### ISSUE TITLE
allow to add Log to custom URL using QR code

### ISSUE THREAD

**Issue by fohlsso2** [mendhak/gpslogger#659]
When using the function to log to custom URL it would be very useful if it was possible to read the URL from a QR code image or similar to avoid tying errors and it allows any other services that utilizes the gpslogger to help users quickly set up a new URL.

**Comment by lenucksi** [comment]
Hi, some time ago I opened a PR (very, very unclean code, mostly since it was needed for prototyping purposes) for such a "provisioning" scenario. Entire profiles, and thus likely by that also custom URLs, could be provisioned by opening a specific URL with a profile file in the browser.

You'd probably have to clean that up, add some sort of hook to a QR code processor and you could be done with it. Maybe even scanning the specific URLs with a QR code processor and then have them opened by GPSLogger could suffice. 
Have a look here: https://github.com/mendhak/gpslogger/pull/567

**Comment by mendhak** [comment]
Yes I would prefer it to be the way lenucksi describes - provision the setting via a custom URL.  Track it here:   https://github.com/mendhak/gpslogger/pull/760

**Comment by mendhak** [comment]
v103 released to market
