### ISSUE TITLE
HTTP sender that sends positions in batches

### ISSUE THREAD

**Issue by nicbou** [mendhak/gpslogger#681]
The custom URL logger simply makes a GET/POST request for every record, right?

If I went offline for a few days, what would happen when I get online? Would it send thousands of requests as fast as it can? I'm worried that this will overwhelm my (possibly bad) network connection, or just kill my server.

I'm going to use GPS Logger to track a long motorcycle trip. I won't always have a data connection. Even when I do, it might be really bad. I don't need the location to be updated in real-time; once a day would be just fine.

Would it be possible to send locations in batches by HTTP, like for FTP uploads? For instance, would one HTTP request per track be possible? It would allow me to have a very lightweight server, instead of an FTP server with a cronjob that monitors the upload directory.

Thanks a lot for maintaining that project. I used it earlier and I simply love how versatile it is.

**Comment by nicbou** [comment]
After a quick look at the code, a shorter way to say it is:

"Would it be possible to have an HTTP sender?"

**Comment by nicbou** [comment]
I agree. Would it be possible to upload GPX or other files as a POST request instead of as an FTP upload? It would be much easier to run a simple HTTP API than some sort of FTP + directory monitoring setup. It could be hosted on AWS for pennies.

**Comment by mendhak** [comment]
It would become an entirely new kind of sender - because now the multipart boundary and body need to be customizable by users.  It would also need queuing, retries, etc.  

File upload is what those other senders were made for - and are built with more robustness as opposed to the heavily adhoc nature of an HTTP POST file upload.  

I'd suggest instead - log the files to phone as normal but get something like Tasker to HTTP POST the file over or Tasker can also run shell commands so you could try a `curl` to post the file over.

**Comment by MiddleFork** [comment]
How about using SFTP and integrating with an SFTP over websockets solution like https://github.com/lukaaash/sftp-ws.

It seems to me this could be the best solution.  Reduced latency and reduced data transfer.
