### ISSUE TITLE
Autostart app when closed?

### ISSUE THREAD

**Issue by evelinlive** [mendhak/gpslogger#694]
Hi, is it possible to make a feature to start app when is killed/closed automatically? (5 mins interval for example).
Same idea for enable location services when LS disable is detected.
Thanks for reply or advise how to do it...

**Comment by mendhak** [comment]
If I'm understanding right, both of your scenarios aren't possible.  

First one - start the app when it's closed, that isn't possible  since the app being killed means that the app has no code running any longer.  Although I have added a bit in the service that when the app is killed it does attempt to restart itself, but it can't recover from being closed.

Similarly for location services - there is no way to enable location services when it has been disabled.  Code can only check that it has been enabled/disabled and maybe even present a dialog box but nothing more.
