### ISSUE TITLE
12//12/18 update having problems reporting to Home Assistant

### ISSUE THREAD

**Issue by flamingm0e** [mendhak/gpslogger#701]
After the update this morning, devices are not staying connected to Home Assistant, using HTTP Headers, or Bearer token.

Access log on my NGINX reverse proxy shows:
`[13/Dec/2018:03:39:33 +0000] "-" 400 249 "-" "-"` like it never even attempts the URL

Going back into the custom URL screen will present me with a 400 response as well, along with "Unexpected code Response{protocol=h2, code=400, message=, myURL}"

Out of my 6 devices I am using GPS Logger on, the only devices exhibiting this behavior are the 2 that I updated this morning.  The other 4 are fine.  Sometimes a reboot of the device connects it temporarily, but then it breaks again a few minutes later.  This same setup has been working for months until today.  If there is something that I can tweak in my NGINX config or any other logs I can provide, I will be glad to help.

**Comment by mendhak** [comment]
What android version do you have, also what are the settings such as
logging interval.

**Comment by mendhak** [comment]
I've just pushed v99 to market, or you can get the latest APK at : https://github.com/mendhak/gpslogger/releases/tag/v99

I've undone one Custom URL change

**Comment by flamingm0e** [comment]
I just saw the update!  Thank you so much.

**Comment by jantman** [comment]
@mendhak I just wanted to give you a heads-up that I ran into the same error after updating to v98, which was fixed by updating to v99. I didn't see this issue until I'd done a bit of debugging to see what the problem was.

I was also using Nginx, and if I had the GPSlogger UI open while enabling custom URL, I got a ``400 Request Header Or Cookie Too Large`` error message.

I'd had the custom URL configured with the default HTTP Headers value of ``Content-Type: application/x-www-form-urlencoded``.

I ran a packet capture on my endpoint server, and it turns out that the HTTP GET request I'm seeing has the Content-Type header duplicated **7,202** times. As in, the HTTP GET is 7,207 lines long (353 KB) - the GET line, the Host, Connection, Accept-Encoding and User-Agent headers, and 7,202 duplicated ``Content-Type: application/x-www-form-urlencoded`` headers.

The end result of this is that Nginx's maximum header size is exceeded by ~10% of the request, and Nginx responds with a HTTP 400 before the request is even finished sending. I'm pretty sure most other web servers can't handle this either.

Hope this info might help.
