### ISSUE TITLE
error while executing job com.mendhak.gpslogger.loggers.customurl.CustomUrlJob@...

### ISSUE THREAD

**Issue by Sergio-Gomez-Lopez** [mendhak/gpslogger#703]
Dear mendhak,
I'm having this error randomly Could not send to custom URL.
Do you know why this happens and how to solve it?
Thanks in advance and best regards,

**Comment by mendhak** [comment]
Enable [debug logging](https://gpslogger.app/#troubleshooting) and try your custom URL again

When you do that you should see a full error message (I can't see the actual error in your title).  You can paste the whole stack trace here if you'd like or paste the whole debug log or mail it to me (gpslogger @ mendhak dot com)

**Comment by jurgenhaas** [comment]
I'm having the same error on one of our family's devices. The others work super stabil but the Samsung Galaxy S8 stops working every now and then. I've managed to extract the debug log which is from a time when such a problem occured:

[gpslogger.log](https://github.com/mendhak/gpslogger/files/3149174/gpslogger.log)

Please let me know if I can provide any more helpful details.

**Comment by mendhak** [comment]
The main error is that the requests time out after 10 seconds. 

> java.net.SocketTimeoutException: failed to connect to example.com/123.456.789.123 (port 443) from /987.654.321.987 (port 36022) after 10000ms

My guess here would be - you are attempting to write to the database right when you receive your request.  Normally this is fine, but there can be several server-side problems which cause the write to be slow, examples are unoptimized DBs, overloaded micro-servers, IO contention.   So while the HTTP request may actually have actually completed 20, 30... 60 seconds later, the GPSLogger app has timed out and can't wait any longer.  

What I'd suggest is to investigate, maybe the DB just needs some indexes/primary keys to help it along, maybe there are too many users.  Or that could all be fine and what you need is a queueing system where the data received is written quickly to a message bus/queue (eg Rabbit, Kafka, Kinesis) and then a separate process actually reads from those and writes to the DB.

**Comment by jurgenhaas** [comment]
Most certainly, I can rule this out. On the server (NextCloud) in my case, there are only 5 users with very little usage. And there is no other traffic on that host which is a dedicated root server on Ubuntu 18. I have optimized setup for all components because I'm also hosting high traffic websites on other hosts with similar setup.

Also, there are different phones being used with GPSLogger and only that single one is having this issue. OK, that's the one which is out of the house most of the time and therefore more often in areas with bad connectivity. I can imagine that the timeout is caused by bad connectivity though, but not the hardware in the backend.

Either way, what I wonder is why GPSLogger stops working once there has been a timeout? Should it not be more tolerant and then just retry when that happened?

**Comment by mendhak** [comment]
OK understood it's not a server side issue, yes it can be a bad connection.  However there is indeed retry logic built in. 

I've set it to [2 tries](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/customurl/CustomUrlJob.java#L107).  I can see retry applied at 13:16:45 and 13:17:32 and the service gets destroyed once in between.  

I can't say what's happening on the phone, though at best I can add more retry (make it 3?) an add a bit more logging around the custom url attempts.

**Comment by jurgenhaas** [comment]
That sounds great. Maybe the number of retries could even be made configurable?

**Comment by mendhak** [comment]
The retry logic is part of the underlying library (jobqueue) - making it configurable adds more complexity but also makes moving off the library harder, so that can't be done.  

I've gone for 5 retries in custom URL and added some more logging to know a retry is happening

**Comment by mendhak** [comment]
v103 released to market
