### ISSUE TITLE
Send to custom URL crashes if password contains a #

### ISSUE THREAD

**Issue by semperor** [mendhak/gpslogger#715]
The password contained various special characters. Among others: $, ~ and {. Only the # led to the crash.

_Originally posted by @semperor in https://github.com/mendhak/gpslogger/issues/709#issuecomment-461140880_

**Comment by mendhak** [comment]
This is very interesting, I will test this out.   Do you get a stack trace or do you happen to have a debug log?  If you don't then I will test it myself and try to get stack trace in the IDE.   I wonder, why would # cause a crash, perhaps it's being interpreted as an anchor.

**Comment by semperor** [comment]
The logging view only reported that the CustomURL task was not running.

**Comment by mendhak** [comment]
I had meant the debug logging rather than log view, the debug log can show stack traces.  But that's OK I found the issue - the code is supposed to remove the `username:password` from the URL first.  But the regex is failing here and not removing it! The URL is being passed as-is to OKHTTP and OKHTTP is not happy with it, so it throws an exception.  I am thinking of a way to deal with this.  After all the regex can get more and more complicated.

**Comment by mendhak** [comment]
OK so a better way is to just move the username password into its own preference dialog. That allows masking the password (issue 716), and also it gets rid of problems with special characters since the whole thing can be taken 'as-is' (issue 715).  So it should solve both problems.

If you are able to sideload, you can try it out:

[APK](https://drive.google.com/file/d/16hRCiPM_NJLcuZCf9d6qTMg4zb8RshlF/view?usp=sharing), 
[signature](https://drive.google.com/file/d/1u1JE0uZLJhft7WyQinJFxRhJcob71efB/view?usp=sharing),
[checksum](https://drive.google.com/file/d/1nEZsoVy7K8AfWd2a2nVbijXTcQD1WaUG/view?usp=sharing)

Preview

![20190214_222454](https://user-images.githubusercontent.com/746276/52821734-a2c4f800-30a7-11e9-9332-b03b6e135cf8.gif)

**Comment by mendhak** [comment]
v100 has been released to market.
