### ISSUE TITLE
Truncated <time> values written to gpx files ?

### ISSUE THREAD

**Issue by MikeParfitt** [mendhak/gpslogger#728]
When I loooked at a .gpx file with a text editor, I saw that the time fields all ended with a decimal point then 3 digits then a Z - presumably to indicate UTC to the nearest thousandth of a second.

Unfortunately, all of them were either .999Z or .000Z instead of a random distribution across the 1000 possible values.

I ran a grep across 7 .gpx files.  In total, there were 5281 time fields
 -> 2599 ended with .999Z
 -> 2678 ended with .000Z
 -> only 4 were not these two values, but I didn't check what they were

My guess is that the high-precision time value is passing through a low-precision variable in most cases, thereby truncating the bits that hold the thousandths of a second.

Is this a bug, or by design ?

**Comment by mendhak** [comment]
This is by design, but kind of.  In most cases this is what I have observed: 
* If you use satellite locations then you will notice .999 or .000.  It's supposed to be .000 but the .999 is probably an outcome of [internal floating arithmetic](https://stackoverflow.com/questions/21895756/why-are-floating-point-numbers-inaccurate).  
* If you use network locations then you will notice real values for milliseconds!  The network time is actually just the device reading its own time, which in turn can come from network or SNTP/NITZ. 


The satellite time should be more precise, you would think, but in most phones the GPS receivers are cheap and designed for power saving rather than precision.  Note that it is accurate, but not precise, so it matches the satellite times with the [18 second gap](https://confluence.qps.nl/qinsy/en/utc-to-gps-time-correction-32245263.html?macroName=sv-translation&desktop=true#UTCtoGPSTimeCorrection-LatestIERSBulletinC)  but what you get is the time of the fix but at a 1 second precision.   At the same time I can't say this will be true for all phones, as the GPS receivers in phones are not really documented and neither are the hacks/shortcuts/workarounds implemented before the location information is passed to the OS and the app as well.  

There's a nice [thread you can read here](https://grokbase.com/t/gg/android-developers/124psdf8c3/how-to-get-accurate-time-stamps-from-android-gps-location) with some of this information.  I've seen users use external bluetooth GPS receivers to achieve millisecond precision.  Sorry I don't think this really answers the question, it's a nebulous area.
