### ISSUE TITLE
Is it possible to disable queueing in the custom url ? i only need the real time location

### ISSUE THREAD

**Issue by soufiene-slimi** [mendhak/gpslogger#734]

**Comment by mendhak** [comment]
The event queue way of sending the custom URL logging is too embedded to disable it.  It's important since it increases the chance of logging when there is poor signal by retrying a few times.  In terms of timing, it is better to parse the location data on the server side by sending the `%TIME` or `%TIMESTAMP` in querystring, rather than using the time that the request was received, as there can be other factors that cause an HTTP request to be delayed.

**Comment by soufiene-slimi** [comment]
Thanks for your response, but my problem is that i only want the real time data and if there is no internet connection for a while it takes long time before flushing all the queue

**Comment by mendhak** [comment]
Yeah unfortunately, I checked the implementation and it's not possible to introduce this option.  The only other way I can think of achieving something like this is going straight to Tasker or AutomateIt - Tasker at least has a `%LOC` parameter and it can make the request without any queueing, so that either it sends through or fails immediately.
