### ISSUE TITLE
Bug when using Points when logging

### ISSUE THREAD

**Issue by Tapter** [mendhak/gpslogger#742]
There appears to be a bug in the latest version:
While logging a long track I also often use the pencil icon to add a point at the current coordinates.
However about every second time, that point is logged at a completely different location (one that the device never saw). I've tried it multiple times, it happens all the time. I can spot that situation when (after entering the description), the accuracy suddenly hops to something like "3.1 km" instead of the 3-5m it previously had. Also the coordinates change considerably. After some seconds it gets the fix again and the coordinates (and accuracy) hop back to the current (real) coordinates.
However like this, I get tracks that have **most** of their points logged 3.1km away (sometimes even more).
also it appears, those wrong coordinates remain the same during the same log, so all points get logged at the same coordinates far away. Example:
![image](https://user-images.githubusercontent.com/17089359/57409837-999c8080-71e9-11e9-917c-fcabc6390dc4.png)

This never happened before.
I'm using v102

for the moment I've stopped using gpslogger because it's unusable to log trackpoints.

**Comment by mendhak** [comment]
Under performance menu do you have GPS as well as network locations?  

This looks to me like network location caching.  I don't know _why_ it's happening unfortunately, I do see it happen though.  So it is better to turn off network/passive locations and only rely on GPS in this case

**Comment by NielBuys** [comment]
I had the same problem Yesterday. The problem is there is not enough cell towers in the area to calculate the position correct.

I wanted to create a new ticket/request today to help with this problem. But on seeing this ticket I am going to respond here.

The accuracy on the network is 2.2km but the accuracy on GPS is 6m. Can't you use the same mechanics as the route log for the waypoints and single point buttons. If the accuracy is more than the "Accuracy filter" setting value. Discard the Network value and try the GPS instead.

Yesterday I only found the setting to disable the network after the hike. On the hike the waypoint button always first selected the network. And I had no way of telling the software to discard the waypoint and try again.

Thanks for the software it works great.

**Comment by mendhak** [comment]
Yep that's what I'm doing here: 

https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L845

The accuracy filter needs to be matched in order for the received point to be processed.  

If you are seeing wild locations out of place, based on cell tower, that's usually the phone caching a network location, and even those wild locations are carrying a good accuracy which matches the filters withi them.  To avoid this noise you can simply stop using network location, it does happen on some phones but I've never found why

**Comment by Tapter** [comment]
It seems that this logic is completely off however.. I've set an accuracy filter of about 20m and it accepted that point with 3.5km accuracy. It even showed '3.5km' for a short moment after saving the point...?
Maybe it's because of what the comment says: "However, if user has set an annotation, just log the point, disregard any filters" ?? I always set a description, so that point is logged even if the algorithm sees a wrong location for a short moment?
I still don't get it why you're able to log tracks correctly but for some reason get a completely different point just when setting a point???

**Comment by NielBuys** [comment]
My accuracy filter was 20m and the accuracy was 2.2 km for the point and GPS logger accepted it. So something must be wrong.

**Comment by NielBuys** [comment]
Find attached the gpx file. If you want to view it. You will see my route is all in the reserve taken by GPS but my waypoints is in town taken by network.
I have a Nokia 5, Andoid 9 if you need the info for bug tracking.
[20190605.zip](https://github.com/mendhak/gpslogger/files/3270930/20190605.zip)

**Comment by mendhak** [comment]
That was very helpful, yes I can see the off-logic which is affecting the positioning badly, all the network based positions are really off.  

Specifically it's this line here:

https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L839

It's OK to ignore the user's time filter and distance filter for annotations.  What I'll do now, I will try to remove that condition there and watch the behavior of annotations.  This can take a while. 

I would suggest to you to stick to satellite (GPS/GNSS) locations in the meantime because even when they're bad they're still better than network locations so this should alleviate some of the jumping

**Comment by NielBuys** [comment]
Thanks for reply, I look forward to the changes, will switch of network in the meantime.

**Comment by mendhak** [comment]
I've put a signed APK in the [pre-release](https://github.com/mendhak/gpslogger/releases/tag/v103).  If you have the ability to sideload you can use that APK.  If you do use that APK you will still receive Play Store updates when v103 is out eventually.

**Comment by NielBuys** [comment]
Thanks I will wait for the update on the play store.

**Comment by mendhak** [comment]
v103 released to market
