### ISSUE TITLE
Auto send now doesn’t work?

### ISSUE THREAD

**Issue by rubakov** [mendhak/gpslogger#745]
Hi!

Thank you for your app, it’s really helpful.
I’ve tried this app today for the first time, and it really does everything I need.

I set up auto reports to e-mail and google drive, and tests where passed successfully. So I was sure it will send me reports in time. 
But it didn’t happen.

I’ve started to investigate issue, and found “auto send now” button.
After I pressed it, I got an error similar to “cannot connect to socket on 127.0.0.1:80 from 127.0.0.1:53357”

So I retried to send test logs - everything went fine.

What am I doing wrong and how to fix this error?

Thank you for your answer in advance.

Here is a picture of this error:

https://yadi.sk/i/mEHqIFuAijTN5w

**Comment by rubakov** [comment]
After a couple of days I decided to re-check my google drive, and I found all files there. I’m happy!

So it seems, that auto upload works, and issue is just in this button.

**Comment by mendhak** [comment]
That error looks like some kind of local VPN or proxy server (or local adblocker?) running, I'm not really sure.  If such a software is running and blocking requests, that could result in the error you're seeing. Is that your email server perhaps

However as you've found it eventually uploaded, so that's good, I just don't know what the 127.0.0.1 address is.
