### ISSUE TITLE
Custom URL Logging - no log to localhost whithout Network

### ISSUE THREAD

**Issue by chlupm** [mendhak/gpslogger#749]
Custom URL Logging requires Network. Is not good when log to localhost or when use special network connections (usb rndis reverse thether). Idea: In conf "Custom URL Logging" add checkbox: "No require Network for log".

Thank You for GPS Logger.

**Comment by mendhak** [comment]
I can't make changes of that nature to the underlying job queue library, the complexity introduced is way, way too much to maintain and also makes moving off that library very difficult in the future.  

I don't really know what 'usb rndis reverse tether' is but if it's making special modifications to the way networking works on Android then that also makes it harder to test on a regular basis, an area where I am severely lacking.   

It would be better if the reverse tether method had a way to inform Android OS that an internet connection exists, instead of pushing the workaround into the app layer.
