### ISSUE TITLE
Poor quality uploads to OpenStreetMap

### ISSUE THREAD

**Issue by mmd-osm** [mendhak/gpslogger#750]
Some users seem to use your app to frequently upload GPS traces to OpenStreetMap which unfortunately don't include any activity at all. Is there some way you can prevent such pointless uploads?

https://www.openstreetmap.org/user/FVbike/traces

// CC: @tomhughes

**Comment by mendhak** [comment]
I'm not sure how to define 'pointless' here.  If it would be based on distance then legitimate users could also be blocked from uploads if all they're doing is recording a single annotation for example.  That's an interesting example you've shown, it looks like a user has left the upload running while staying in one location but due to, potentially, environmental reasons the location is jumping around.

**Comment by mmd-osm** [comment]
Right, GPS is known to be somewhat noisy, e.g. when you leave a logger running for some time, it will inevitably collect some jumping location.

In the given example, the logger seems to accumulate more and more points for the same track, and uploads the current track about every hour.

I wonder if it might be possible 
* to filter out some of the noise (I think http://gis.stackexchange.com should give some ideas)
* check that the track's bounding box has a certain size before uploading
* upload a track only once, skipping those intermediate versions

Uploading single annotations isn't a concern at all, it's more the kind of "continuous uploading of noise".

**Comment by mendhak** [comment]
Hmm, I can have a look at any ideas around filtering (ie jumping) on the GIS site but I'm not sure how that would help here, noise will always exist as many devices are different.  Bounding box comparison isn't suitable either as users won't know what a suitable size should be.  

Uploading the track just once per file sounds pretty good but again brings about troubleshooting - since the auto upload feature sends files at a regular interval and there is a user expectation that GPS tracks are uploaded to destinations at regular intervals.  Though I wonder if the OSM API allows trace file overwrites?  I couldn't find it in the API docs.


> There's also some privacy aspect here, as we know pretty well now, where the user spent the last x hours (might be their home location).

Following the API: 

https://wiki.openstreetmap.org/wiki/API_v0.6#Uploading_traces

The default for the OSM upload feature in GPSLogger is visibility = private.  But the user can also pick between 'public' 'trackable' 'identifiable'
