### ISSUE TITLE
GPS Logging Airplane

### ISSUE THREAD

**Issue by dshanske** [mendhak/gpslogger#775]
This is sort of a weird request. I am not sure if there is a way to add this to GPSLogger.

When I fly, I am interested in tracking my location. I was able to extract location manually from the plane wifi, which supplies it on a local site.

I would like to have this logged in the same places I log my other information. But I am not quite sure how to do that, if it is even possible.

I thought I would open an issue to see if there is a way.

**Comment by mendhak** [comment]
Can you give some detail about the manual bit.  How did you extract your location from the aircraft's wifi?

**Comment by dshanske** [comment]
https://david.shanske.com/2019/11/07/airplane-wifi-location-tracking-to-tasker-to-compass/

**Comment by mendhak** [comment]
Hmm yup that's a niche request for sure.

I think there are a few things you can try.  First is, since you are using Tasker's Java, you can try writing straight to the GPSLogger file.  For this you'd need to know what file GPSLogger is writing to.  Either make it super-predictable like `yyyyMMdd.gpx` or give it a static name that doesn't change. 

Then it's a matter of building the XML, you can [get an idea of it here](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/gpx/Gpx10FileLogger.java#L261) or just open a GPX and look  at it yourself, take it to the minimum required.  Most importantly note the [bit that is added at the end to close off the XML file](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/gpx/Gpx10FileLogger.java#L332).



Then append to the file

```javascript
var yourBuiltUpXml="<trkpt... lat... lon...</gpx>"
writeFile("/sdcard/...gpslogger/...static.gpx", yourBuiltUpXml, true);
```
You'll probably want to hardcode that XML and try it out on a file locally first before flying.

One other caveat is that if GPSLogger is writing at the same time as Tasker, there can be conflicts, file corruption, errrors - it's an unknown

**Comment by mendhak** [comment]
Ah no - just realized that the append needs to happen at a specific position - you can't just have the `</gpx>` repeated constantly.  So you'll have to read the entire file into memory and write it back.  It gets complicated.

```javascript
var file = readFile("/sdcard/...gpslogger/...static.gpx");
var lines = file.split("\n");
var yourBuiltUpXml="<trkpt... lat... lon...</gpx>";
lines.splice(lines.length-2, 0, yourBuiltUpXml, "</trkpt>\n", "</trkseg></trk></gpx>");
var newFileString = ""
for (let i = 0; i < lines.length; i++) {
    newFileString += lines[i];
}
writeFile("/sdcard/...gpslogger/...static.gpx", newFileString, false);

```

**Comment by dshanske** [comment]
I would stop Gpslogger in the case of a connection to avoid corruption, but sounds like my current hack may be the best way for now.
