### ISSUE TITLE
GPS Weeknumber Rollover

### ISSUE THREAD

**Issue by RonnyRauchmelder** [mendhak/gpslogger#779]
Hallo,
for my work in Openstreetmap I used a Travelreceiver BT-Q1000X in the last years. This GPS logger now has the GPS Week Number Rollover problem. Date and time are recorded incorrectly. Since the BT-Q1000X delivers very accurate position data, I do not want to do without it. My idea is to connect the BT-Q1000X via Bluetooth and the app "Bluetooth GPS Provider" to the smartphone, to allow wrong locations and so have very accurate GPS data in the smartphone. I record these locations with GPSLogger. In the recording, however, I have the date and time the BT-Q1000X delivers. So wrong times. Is there a way to configure GPSLogger to get the app's date and time from the smartphone? Only position data should be taken over by the BT-Q1000X?

With best regards

**Comment by FalkTannhaeuser** [comment]
I observe the week number roll-over problem starting from November 3, 2019 - the date in the GPX file from this day is March 19, 2000 (difference of exactly 7168 days = 1024 weeks). This occurs 210 days = 30 weeks after the official epoch roll-over of April 7, 2019. The device is a Samsung Galaxy S4 (GT-I9505) with Android version 5.0.1 (yes I know it's old...). Would there be a possibility to fix this in GPSLogger? Best regards

**Comment by mendhak** [comment]
Well, I never thought a [decision made before I was born](https://nakedsecurity.sophos.com/2019/04/05/serious-security-gps-week-rollover-and-the-other-sort-of-zero-day/) would come back and affect me :grin: 

I thought about introducing a 'use device time' option but that can introduce other problems especially if the time is wrong due to additional external factors, that's a lot more troubleshooting with users for me. 

I am thinking instead, what about detecting an 'unusual date' and applying a correction on it. By 'unusal date', I could either mean actually doing a subtraction and checking for 2^10 weeks, or it could be  just comparing the given date is before  2019-04-06.  In either case I then add +1024 weeks to the date.  I am leaning towards the latter; just checking for a 'less than' rather than exact subtraction.

**Comment by mendhak** [comment]
OK I have a potential fix, but I have no way of testing it.  Even in the Android emulator, when I can manually send a location, I cannot set an old time on the location object.  So for this you will need to download the APK, allow sideloading APKs onto your device, then test with your devices.  

The logic I have applied is: If the date is older than April 6 2019 23:59:59, then I take the date and add 1024 weeks (619315200000 milliseconds).

The APK is here:  https://github.com/mendhak/gpslogger/releases/tag/v104 under assets.

The 'corrected' time should appear in all file formats.

**Comment by FalkTannhaeuser** [comment]
Doesn't work at all for me - it never obtains any GPS fix, and it stops when trying to put it in background mode. Could it be that some of the commits between the official v103 release and the week-rollover fix broke backward compatibility with Android 5.0.1?

**Comment by mendhak** [comment]
I just tested in an Android 5 emulator and this task just uncovered something else...

Yes there's a major change.  [Starting November 1 2019, all apps must target API version 29](https://support.google.com/googleplay/android-developer/answer/113469#targetsdk).  I had dutifully made this change, however, part of the upgrade required me to use code that requires a minimum level of SDK 24 (Android 7).  So that's why the APK didn't work for you.  I'll have to find a way for the old and new to coexist.

**Comment by mendhak** [comment]
Tracking the SDK upgrade in #784 

You should uninstall the APK I gave, it's of no use to you.  If I can find a way to make this backwards compatible I'll update later.

**Comment by FalkTannhaeuser** [comment]
I somehow managed to compile the app from source (official release from master branch + cherry-picking the [gps-week-rollover-issue779](https://github.com/mendhak/gpslogger/commit/32fcf91768ed38bdbc0e7afe4032144a563ba31e) commit) - first time ever that I installed the Android tool-chain and built an app...
Seems to work now!

**Comment by tohis** [comment]
Since November, I've also had wrong dates recorded into the GPX files. My phone is Samsung Galaxy S4 GT-I9506, with LineageOS 15.1 (8.1 Oreo) installed. I tried your "103-weekrollover.apk" and it solved the problem for me. I got signal and the date in the log file was now correct.

**Comment by mendhak** [comment]
@tohis  still seeing this behavior?   In the log file with mixed results, are the incorrect dates followed by correct dates later?  The incorrect dates are they from a certain 'source' for example, do you see all the satellite source times are corrected but the network source times are incorrect?

**Comment by tohis** [comment]
^ Mixed dates problem went away after updating to 103-weekrollover.apk so no worries.

I found few log files (see the attachment) made by earlier version which had few correct dates in the beginning, and 2000-xx-xx in all the rest. Those first ones could indeed be from network before getting the gps fix, however there seem to be <src>gps in all of them.

[20191206124937.gpx.txt](https://github.com/mendhak/gpslogger/files/3961790/20191206124937.gpx.txt)

**Comment by mendhak** [comment]
Copy pasting from #784:

After a lot of trying and digging - I've found that Google [accidentally removed an API](https://issuetracker.google.com/issues/141019880) instead of deprecating it.  So the code I wrote to get NMEA listener working with the newer SDK means it won't work at all for older devices.   It will be reinstated in SDK 30.  

There is a [workaround here](https://stackoverflow.com/questions/57975969/accessing-nmea-on-android-api-level-24-when-compiled-for-target-api-level-29) involving reflection and at first glance the complexity is increasing.  This isn't a great situation - it'll be extremely error prone, and what effect does it have on stability?   How to test this? 

And even though this is a temporary fix, there's nothing more permanent than something temporary.  This will hang around for a long time.  

I've spent a day or two finding my old Nexus 5 and I finally found it; but to my dismay the location function isn't even working properly so I'm troubleshooting that.  (This particular issue cannot be tested in an emulator).  

Right now it feels like I'm [shaving the yak](https://seths.blog/2005/03/dont_shave_that/) :laughing:

**Comment by mendhak** [comment]
APKs have been [updated](https://github.com/mendhak/gpslogger/releases/tag/v104) with the new workaround. 

@FalkTannhaeuser  if you could try the ones I've uploaded

I tested on a Nexus 5 device.  It looks working.

**Comment by FalkTannhaeuser** [comment]
Works with https://github.com/mendhak/gpslogger/releases/download/v104/gpslogger-103-weekrollover.apk and dates / timestamps look OK so far.

**Comment by mendhak** [comment]
v104 released to market.
