### ISSUE TITLE
[Battery] Consider switching to the activity recognition transition API

### ISSUE THREAD

**Issue by calle300** [mendhak/gpslogger#800]
The way activity recognition seems to be implemented, gpslogger wakes the phone at every set logging interval to check if any movement has been recorded.

This also means that the phone will wake even if no movement has been detected, using unnecessary battery. 

An example. Let's say the logging interval is set to 60s. Waking the phone every 60s for 8h (a night) is 480 wakelocks/night. I would assume this causes considerable battery drain even if no locations are being recorded. 

So - I would suggest switching to the activity detection transition API. 

https://developers.google.com/android/reference/com/google/android/gms/location/ActivityTransition 

That way gpslogger will receive an update when the user starts moving (action will be to start logging) and when the user stops moving (action will be to stop logging).

Expected result: no more wakelocks when the user is not moving, saving a considerable amount of battery.

**Comment by mendhak** [comment]
Unfortunately since the app is now on F-Droid, I can't use Google Play Services any longer.  I've been on keeping an eye out for an alternative open source library/implementation but nothing has come up, at best I've seen some academic proof-of-concepts.  I don't expect anything good to emerge anytime soon either because it appears that activity recognition relies on the quality of learning models and large tech companies tend to not share those.
