### ISSUE TITLE
Move translations to Hosted Weblate

### ISSUE THREAD

**Issue by comradekingu** [mendhak/gpslogger#818]
Hello, I want to contribute to the translation effort, but Crowdin is a lackluster tool that employs a whole lot of spying and tracking. It would be great if the translations could be moved onto the libre Hosted Weblate service instead :) Self-hosting is also an option of course.

A lot of GPS/map software on there already, (with more to come).

https://hosted.weblate.org/projects/osmand/
https://hosted.weblate.org/projects/getback_gps/
https://hosted.weblate.org/projects/routeconverter/
https://hosted.weblate.org/projects/openorienteering/
https://hosted.weblate.org/projects/trackbook/#information
https://hosted.weblate.org/projects/ghini/
https://hosted.weblate.org/projects/cityzen/#information
https://hosted.weblate.org/projects/trustroots/

Just send a request at https://weblate.org/hosting/ and the hosting is gratis since this is a libre software project.

**Comment by comradekingu** [comment]
@mendhak One language with coverage in 10 years is less than ideal.
I can help set it up :) https://hosted.weblate.org/hosting/

**Comment by mendhak** [comment]
Hi that's a good suggestion, I've heard of Weblate before.  I'm not keen on any kind of self-hosting though as it presents another moving part that would have to be managed, while if hosted Weblate goes down at least it is a shared suffering.  

I will play around with hosted Weblate.  Observations so far

* Source control integration - can it do pull requests? (Yes it can) 
* And also can it use the Android locale folder names like `values-pt-rBR` (Will test this)
* And set up a webhook to push from Github to weblate (Will test this)
* Can it do screenshots with strings, Crowdin does this quite well by highlighting areas on screenshots. I think Weblate shows the associated screenshot. I don't think that's too bad. 
* 

Something that isn't clear to me.  I created a project and a 'Glossary' project was created with it.  I'm looking at other projects, and the documentation, and it's still not clear what this Glossary's purpose is. An example might help me understand.

**Comment by comradekingu** [comment]
@mendhak 
Yes it can use the Android folder names. Use a * for the filemask naming.
You can do screenshots, but the tool is a little cumbersome. There is a lot of other context you can add too.
It also does a 30 character limit for titles, as per the new guidelines.

Glossaries are entries used for a project. You can have a list of specific project-wide words to look out for, or per language.
It is also possible to have forbidden translations, which avoids common mistakes and ensures consistency as a compliment to flags. If you add "kingu" as an admin I can help where possible.

**Comment by mendhak** [comment]
Yeah I'm still evaluating a bit but assuming everything's OK I'll need some time to announce and migrate Crowdin over as it's not a simple overnight job, I've been using it for 10 years and there are quite a few users active there.  

Encountered another issue yesterday, I don't know if this is expected behavior.  I made some test translations, and Weblate issued [a pull request](https://github.com/mendhak/gpslogger/pull/948).  So far so good. 

I then made more changes but those seem to be stuck in a pending state.  It's been over 12 hours, I thought the pull request would just keep updating with changes.  

![image](https://user-images.githubusercontent.com/746276/151757728-b5b0f8ae-9af0-46b4-bcd0-05f46c6c856c.png)

Maybe I need to ask this question over in weblate's github repo

**Comment by mendhak** [comment]
Aaaah this is it.  So glad I checked, I was about to hit submit on an issue and embarrass myself over there.  Glad I can limit the scope of my embarrassment. 

![image](https://user-images.githubusercontent.com/746276/151760048-f14fd7e8-4fac-47f3-bcd6-471983291489.png)

**Comment by mendhak** [comment]
I've added a Weblate badge and link to the README.  Sorry I am going to decline both of your pull requests, you've simply changed too many things unrelated to the move, and I don't want to lose a lot of the translation work already done, even if they are mostly minor source string changes.  

https://github.com/mendhak/gpslogger/pull/949   
https://github.com/mendhak/gpslogger/pull/950

**Comment by comradekingu** [comment]
@mendhak 
That took me hours to do, and I looked at every little string in the UI to do it.
It has nothing to do with moving away from Crowdin, as Crowdin doesn't add or hold any value.
Moreover, Weblate actually handles fuzzy strings correctly, so no strings are lost. This means no good effort is wasted, but it becomes easy for everyone to get there now. The choices are deliberately made to not introduce errors in translation.
The reason a lot of strings changed is the quality was equally poor.
Instead of being a specialty program it could have utility and appeal to normal people.

When you move to Hosted Weblate, you attract a lot of attention, and I generally ask people to translate projects that
do translations right, etc, etc.
What you are instead doing is ensure every fix has to be an iterative process of continual changes, that through some miracle could end up to be consistent at that, but most certainly won't.

I had a lot more stuff planned.

**Comment by mendhak** [comment]
I see I think I'm understanding what you're saying, sorry to appear harsh due to the closure, but it would have been better to discuss it first. I'll explain, the reason is that I've got limited time and effort available to maintain this app,  so I evaluate it based on perceived overhead and maintenance required to me. 

Right now the focus is only to move to weblate, not anything else.  The PRs also had no explanation or context. So seeing them with the extra changes made no sense to me, it was just additional noise. And I'm not an expert at weblate so I can't be expected to know everything about it right away including the fuzzy thing, so again,  a large pr with zero context means it's only going to overwhelm me. 

Yes I think you're right,  it probably won't reach a consistent end state,  but it will need to be iterative because that's all the mental energy I can afford. Hope that's all making sense now.
