### ISSUE TITLE
v111: Can't write to file that GPSLogger didn't create

### ISSUE THREAD

**Issue by TimoWilken** [mendhak/gpslogger#886]
I'm using GPSLogger v111 (from F-Droid), logging to `/storage/emulated/0/Documents/Sync/gps/`. I'm also using [Syncthing](https://syncthing.net/) on the same device to synchronise the CSV and GPX files that GPSLogger creates to my other devices.

Unfortunately, when I edit a file on my laptop such that Syncthing writes to it on my phone (where GPSLogger runs), and then I start logging to that file, GPSLogger can't write to it any more, showing the error messages `Gpx10FileLogger.write` (for GPX 1.0) and `Could not write to file` (for CSV). When I delete/move the file and start logging in GPSLogger, it can create the file and write to it fine.

On v109, everything was fine. I'm on a rooted Android 11 (LineageOS 18.1). I have granted GPSLogger permission to "Allow access to media only" under "Files and media" (the only other option there is "Deny").

In the screenshot below, the messages at 21:57 show what happens when both the GPX and CSV files were edited by Syncthing. At 21:58 and 00:18 respectively, the GPX and CSV file were moved away. At 00:19, both were moved away. Later updates succeeded, even with the files still there, but not changed by Syncthing.

![Screenshot of GPSLogger with error messages: "Gpx10FileLogger.write" and "Could not write to file" (for CSV)](https://user-images.githubusercontent.com/3159813/121823694-7250f100-cc96-11eb-94a5-606a61112dc4.png)

**Comment by mendhak** [comment]
This is due to [scoped storage](https://www.androidcentral.com/what-scoped-storage) which was part of v111 due to an SDK upgrade (it was necessary).  I believe the app the creates is the one that 'owns' that file.  I would assume that if Syncthing is able to overwrite a file, it's not using Scoped Storage, but it does mean that GPSLogger loses ownership.  I'm sort of guessing here, I've not done this workflow myself, but it's the only explanation that makes sense to me.  I think you'll have to stick to 110 if you want to keep using the Syncthing editing way then.

**Comment by mendhak** [comment]
Hi all, finally v117 is on F-Droid.  The app will now ask for a manage storage permission (on Android 11+) when you choose the 'save to folder' setting.  In my emulator testing, only on Android 11+, I was also able to save to SD card.  But not on any other OS version. 

There's also a graphical folder picker for files and folders so you don't have to type it in anymore.  The folder picker is for saving the log location, the file picker is for SFTP private key path.  

I'm now going around and closing a bunch of issues related to folder permissions.
