### ISSUE TITLE
getstatus: no info received

### ISSUE THREAD

**Issue by andreapx** [mendhak/gpslogger#891]
Hi!
I've been using GPS Logger for long time, automated with Tasker -> awesome!!! Thanks!
I'm trying to get GPS Logger status since sometimes it stop working and I realize it hours later.
I've setup a profile that listen to intents "com.mendhak.gpslogger.EVENT and i can receive %gpsloggerevent and %startedtimestamp when GPS logger starts, but when I send the intent getstatus:true, i don't receive anything, or...I don't know where to read the status info.
Thanks!

**Comment by mendhak** [comment]
I was able to recreate the problem. On starting logging, the broadcast is sent.  When requesting it via Tasker as `getstatus:true`, but nothing was happening because this value was null:

https://github.com/mendhak/gpslogger/blob/5512d8711f865799770c45592e76ff1b34e7ef6e/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L1053-L1055

But looking at the commit this has been a problem for 4 years!  :grimacing:

I can deploy this to F-Droid, it'll probably take a week to appear I think.  

If you want to test it now you can use this APK below, but note that it's incompatible with the F-Droid version. 
You'll have to uninstall the F-Droid version to use this, and vice versa.  

[gpslogger-111-tasker.zip](https://github.com/mendhak/gpslogger/files/6857871/gpslogger-111-tasker.zip)

**Comment by mendhak** [comment]
I've published [Release 112](https://github.com/mendhak/gpslogger/releases/tag/v112), so F-Droid should build this update in a week or so.

**Comment by andreapx** [comment]
Cool, thanks a lot!!!!!!
I'll try and I'll give you a feedback as soon as it will be available in F-Droid!

**Comment by andreapx** [comment]
It does work now, thanks!
Though...it responds with "started" without any info about satellite fix or logging status.
I'm creating this Tasker profile because sometimes it happens that GPSLogger starts, but it doesn't start logging. Is there a way to know if it's logging?
Thanks again!!!

**Comment by andreapx** [comment]
P.s. I don't see the "Buy me a coffe" link on your GitHub page...

**Comment by mendhak** [comment]
> It does work now, thanks!
> Though...it responds with "started" without any info about satellite fix or logging status.
> I'm creating this Tasker profile because sometimes it happens that GPSLogger starts, but it doesn't start logging. Is there a way to know if it's logging?
> Thanks again!!!
> 
> ![immagine](https://user-images.githubusercontent.com/13846728/127330946-bbad4eed-4fad-447a-ad7e-b1e910108e5e.png)

There isn't a good way to know, short of introducing a custom broadcast on each point that gets logged.  That would have to be a new feature.  A potential workaround could be to get Tasker to read notifications and look at the GPSLogger one?



> P.s. I don't see the "Buy me a coffe" link on your GitHub page...

Thanks for the thought, I did remove it a while ago because I'm not actively developing, but if you want: https://paypal.me/mendhak

**Comment by andreapx** [comment]
>  
> There isn't a good way to know, short of introducing a custom broadcast on each point that gets logged. That would have to be a new feature.

Waiting for it 😜 

>A potential workaround could be to get Tasker to read notifications and look at the GPSLogger one?

Done, thanks for the hint!
