### ISSUE TITLE
gdrive sync missing from latest download

### ISSUE THREAD

**Issue by liljenstolpe** [mendhak/gpslogger#903]
Greetings,

I've been running gpslogger for quite some time on a Pixel 3.  I just got a Pixel 5a, and noticed that gpslogger is no longer on play store (sorry for all the grief that play store has caused you).  I pulled down the latest APK from fdroid, but now I can't sync to gdrive.  Is that intentional, or has something broken?

Chrisotpher

**Comment by mendhak** [comment]
Hello there, yes that's intentional.  FDroid doesn't allow proprietary libraries as part of [their inclusion policies](https://f-droid.org/en/docs/Inclusion_Policy/), and the ones being used for GDrive weren't opensource, so it had to be removed: Google Play Services.  

If you're looking for GDrive I'd suggest get the APK from release 106:  https://github.com/mendhak/gpslogger/releases/tag/v106

As you've seen development is stalled, there haven't been any major changes in the recent versions aside from SDK upgrades and some bugfixes.

**Comment by mendhak** [comment]
version 122 now has Google Drive reimplemented:  https://f-droid.org/en/packages/com.mendhak.gpslogger/ 

Please give it a try, it should function as before.

**Comment by liljenstolpe** [comment]
thx.  Will try later this week.
