### ISSUE TITLE
[IDEA] Add dark mode option

### ISSUE THREAD

**Issue by 3Domse3** [mendhak/gpslogger#906]

**Comment by mendhak** [comment]
So I had a go at this and [followed these instructions](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme).   Surprisingly.. the app is kind of almost there.   It's kind of weird but sort of works. 


![image](https://user-images.githubusercontent.com/746276/134817260-1e96d15e-e04b-4e11-bacc-443ec2fee395.png) ![image](https://user-images.githubusercontent.com/746276/134817264-9c3526ac-6c40-45ad-a4f6-74f152c796a8.png)

But what hasn't worked is the drawer.  It's been years since I implemented this so I'll need to figure out why it's 'hardcoded'. 

![image](https://user-images.githubusercontent.com/746276/134817276-614d477e-02b6-42a5-9af7-a4ca3a7976b8.png)

**Comment by mendhak** [comment]
Actually how's this

![image](https://user-images.githubusercontent.com/746276/134822782-3eec9d12-425a-4e74-9475-984a38cd98f6.png)


And I was able to make the drawer dark too.  

![image](https://user-images.githubusercontent.com/746276/134822792-225a825d-7316-4e0b-af33-5813e488b447.png)


Preference screens

![image](https://user-images.githubusercontent.com/746276/134822809-f214cade-e72d-43d9-add4-479575710201.png)

**Comment by mendhak** [comment]
If anyone's up for testing I've put an APK here:  https://github.com/mendhak/gpslogger/releases/tag/v118-rc1

**Comment by 3Domse3** [comment]
@mendhak Would a true/AMOLED dark-mode be easily possible too or just the grey/dimmed version you posted here?

**Comment by mendhak** [comment]
It's not easy to do a true black though I was able to darken it further.  I did try out a true black, but a lot more rework was required for that around the icons, coloring and text.  Also it was getting more difficult for me to read and was hurting my eyes.

I was able instead to darken the screens a bit more, and I think I coincidentally ended close to #121212 and learned that it's a good balanced dark color for text and colors.  https://material.io/design/color/dark-theme.html#properties  Not that I I do much of material design, just the explanation made sense.  I still had to modify a few icons to meet this darker black, UI work is hard! I am not a UI person.  

Newer screenshots: 


![image](https://user-images.githubusercontent.com/746276/135171879-ee9dd09d-acad-42ef-b19e-67359d90dd7c.png)


![image](https://user-images.githubusercontent.com/746276/135171978-fcf481e8-1f24-4d0b-923f-bf3d0cb88c16.png)

![image](https://user-images.githubusercontent.com/746276/135171907-fbc19367-1028-41f2-b169-3071faefb592.png)


I also added an option to let user set the theme manually or follow system mode. 

![image](https://user-images.githubusercontent.com/746276/135171971-4fcab0ad-2792-41d3-8cf8-2af72cafe0bd.png)

**Comment by mendhak** [comment]
New APK available at:  https://github.com/mendhak/gpslogger/releases/tag/v118-rc2

**Comment by 3Domse3** [comment]
Looks really good 👍🏻 
Thanks for adding dark mode THIS fast! :D

**Comment by 3Domse3** [comment]
@mendhak 

Although selected, on my Galaxy S8, dark mode doesn't work/change the app 'theme'

**Comment by mendhak** [comment]
Did you exit the app and 'dismiss' it from the task view as well? I tried some emulators and in some cases I had to properly exit it, dismiss it, and then reopen to see the dark theme. 

Also the theme won't apply if you're going through the permission prompts.

**Comment by 3Domse3** [comment]
> I had to properly exit it, dismiss it, and then reopen to see the dark theme.

What do you mean exactly? I selected it, closed the app in the multi task view, and reopened it

(Maybe add a button after changing the theme, which auto closes and restarts the app)

**Comment by mendhak** [comment]
Yes I think what you described pretty much.  From the menu I did exit, then I pressed the square task view and swiped it away.  On reopening the dark view appeared.  

I can try in an emulator tonight, but I am sure I did a Galaxy phone of some sort.  It's one of the [list here](https://support.genymotion.com/hc/en-us/articles/360007473658-Supported-Android-devices-templates-for-Genymotion-SaaS).  

I think I wasn't able to force an exit from that screen, or force an app theme reload, because when I did try it, the service that's running in the background was getting killed in a weird way, and was causing the app to crash.  Android has a very strange restriction where the service needs to be started within 5 seconds of the app start, but when I applied a theme, it was losing track of that 5 seconds and crashing right away. So I had to make the user do the exit/reload, though I can play with this a bit more.

**Comment by mendhak** [comment]
What about 'follow system' - when you go into battery saver does it go dark?

**Comment by 3Domse3** [comment]
> I am sure I did a Galaxy phone of some sort. It's one of the [list here](https://support.genymotion.com/hc/en-us/articles/360007473658-Supported-Android-devices-templates-for-Genymotion-SaaS).

It's an older Android version listed than my phone has but it's listed.


> What about 'follow system' - when you go into battery saver does it go dark?

Also doesn't work.


But it's not a big problem. It's an older phone and I just wanted to let you know. No need to hurry and fix it :)

**Comment by mendhak** [comment]
I tried it on an emulator just now, Galaxy S8. Recording:

https://user-images.githubusercontent.com/746276/136076783-cd58371d-b812-42a7-a3c3-c5f0ca32f697.mp4

The other way this should work is, if you have "Follow System" selected, and the OS goes into battery saving mode, it should get picked up and dark mode gets applied.  But in the Genymotion S8 emulator I cannot enable Battery Saver, the tile doesn't seem to be responding.

**Comment by mendhak** [comment]
Also which APK did you try, was it 118-rc2, or 118?  

Try the 118 APK:  https://github.com/mendhak/gpslogger/releases/tag/v118

F-Droid is currently [broken](https://monitor.f-droid.org/builds/build) due to the recent Let's Encrypt CA expiry so it will take a few cycles before they can release the APK.

**Comment by 3Domse3** [comment]
I used 118 and I always install the Github version.
The issue resolved itself somehow... Did a 7h measurement after installing it and without me doing anything, it's in dark mode now :)

**Comment by mendhak** [comment]
> I used 118 and I always install the Github version. The issue resolved itself somehow... Did a 7h measurement after installing it and without me doing anything, it's in dark mode now :)

I should add that to the FAQ for this.  How to enable Dark Mode?  Go for a walk!  :laughing: 

Anyway good to hear.  Thanks for this idea, I like the dark mode, I use the 'log view' because it looks like a terminal.
