### ISSUE TITLE
[feature request] option to delete .csv files and other data file types from mendhak folders

### ISSUE THREAD

**Issue by qsysopr1** [mendhak/gpslogger#928]
Troubleshooting the new csv upload to custom URL function leaves multiple days csv files which all upload periodically.
It is desirable to clear out old csv files periodically.
I would imagine that using the reset entire app function would do this, but that is rather extreme.
Meanwhile navigating to the folder via terminal emulator is cumbersome.

**Comment by mendhak** [comment]
I have tinkered a bit and I've been able to add a rudimentary dialog which lets a user select the files to delete, manually.  Is that worth trying?  Here you can see a file dialog with multi seelct. 

![image](https://user-images.githubusercontent.com/746276/146756658-d596bfee-9cfc-4dc7-8479-2a6edc8b29fd.png)

I've not made this an automated process.  In the past it's been requested to automatically delete a file when an upload occurs, but because uploads aren't reliable, and deleting is a destructive action, the risk is too large, there could be data loss.

**Comment by qsysopr1** [comment]
That works for me,  In the meantime I added a shell app that cd's into the
correct directory as part of its startup (which is really the main nuisance
 of deleting files) and then rm them manually, so if there is not a lot of
demand for this feature from others maybe don't worry about it or put it
toward the bottom of your list.

**Comment by mendhak** [comment]
v120 is in the [releases](https://github.com/mendhak/gpslogger/releases/tag/v120) and [on F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/)
