### ISSUE TITLE
Force turn on mobile internet if it turned off

### ISSUE THREAD

**Issue by analitic1983** [mendhak/gpslogger#939]
Please add option:
Force turn on mobile internet if it turned off, for saving gps coordinates. Make it turned off back after save.

Coordinates not saving periodically, because mobile internet was manually turned off.
My device Xaomi 9A.

**Comment by PersianCoders** [comment]
Hello dears,
Sometimes the mobile antenna goes off and it is necessary to go to airplane mode once and return the antenna again.
This is great if it is done automatically, because sometimes I do not have access to a mobile phone and there is no one to do it manually.
The program will do this automatically when the antenna goes off.


thanks a lot

**Comment by mendhak** [comment]
Hi both I'm not looking to add this feature into GPSLogger, it's not part of the scope or intention of gpslogger, and it adds more a lot more complexity to the maintenance.  I would suggest mobile data to be controlled via something like Tasker/AutomateIt.  The upload feature (including Custom URL) does wait for an internet connection to be available so it should upload the file then.
