### ISSUE TITLE
Config Profiles/Scheduling

### ISSUE THREAD

**Issue by gaberad** [mendhak/gpslogger#95]
It would be good if we could create profile with different configs, to be able to quickly switch between them and schedule them based on the time of day (or integrate it with something like tasker).

For example, lets say we create two profiles: Day & Night.

Day polls every 10 mins
Night polls every 2 hours

During the day (configurable, but say 7am -6pm) have it use the Day profile, since you're more likely to be moving around.

Then at Night (6pm-7am, or midnight-7am etc), it switches to Night profile when you're sleeping etc so it polls less, and maybe saves on battery?

At the very least, having the ability to quickly switch between profiles would be quite useful, I think.

**Comment by pigmonkey** [comment]
This is the one feature that is missing for me.

I use GPSLogger to record tracks for different activities (hiking, biking, running). For each of these different activities I have different settings in the Performance tab. Remembering my preferred settings for each activity, and then remembering to set all of them before I begin the activity, gets a bit annoying.

**Comment by rstarkov** [comment]
How I'd like to use profiles: low logging frequency when on battery power (1 in 15 minutes), high frequency when charging (every second). Switch between the two profiles using Tasker.

**Comment by mendhak** [comment]
A mere 4 years after this was first requested, I have started working on the [profiles](https://github.com/mendhak/gpslogger/tree/profiles) branch.

I've got an APK if anyone is interested in testing:
https://www.dropbox.com/s/9c761dpimbwmnbd/gpslogger-70-profiles1.apk?dl=0

A header's been added to the drawer.  Pressing it brings up the list of profiles (only `Default Profile` by default)

`Add` will allow creating a new profile.  The profile gets written to a `.properties` file on disk when switching to another profile.

I still need to create an intent receiver that allows switching profiles - this is how Tasker would invoke a profile switch.

I still need to work around a [nasty bug](https://code.google.com/p/android/issues/detail?id=6641) in a clean manner. Basically I try to write all the preferences to the `.properties` file.  But preferences that are false booleans get ignored.  This causes weird behavior when switching between profiles, as a boolean set elsewhere then overrides another profile's value because it wasn't set earlier. 

I still need to figure out what that drawer background image should be.  Could use random material design wallpapers, could have it as a solid thing.  Not sure.

![image](https://cloud.githubusercontent.com/assets/746276/12607449/e19ba262-c4cc-11e5-9d9f-49e68810fe32.png)

![image](https://cloud.githubusercontent.com/assets/746276/12607456/e7fe427c-c4cc-11e5-8045-ee6dc7ef27d1.png)

**Comment by mendhak** [comment]
Added intent receiver so you can change profiles via tasker
Also ensured that profiles don't overwrite each others' settings


https://www.dropbox.com/s/zdbvtncikehup67/gpslogger-70-profiles2.apk?dl=0

**Comment by mendhak** [comment]
Hehe, I don't think anyone's seeing this but I'm updating the thread anyway. 

Simplified the header, localized the strings involved.  Added an Intent receiver so that you can switch profiles via tasker.  

I couldn't find a non-crude way to  inform the user that long pressing a profile name will delete it, so I've just stuck it in the FAQ.  Adding it to the profile list wasn't working out with the current control.  

Here's the 3rd update, I think this is pretty much it so I'll merge this into master soon.  

https://www.dropbox.com/s/3kikuc73e16uclb/gpslogger-70-profiles3.apk?dl=0

**Comment by pigmonkey** [comment]
I, for one, am seeing this and am excited for the next release. :+1:

**Comment by thewholelifetolearn** [comment]
No, no. I think it was the last feature I was waiting for. I'm quite excited for this new release. Thank you a lot for the work you have done. :+1:

**Comment by mendhak** [comment]
`v70 released and will appear in market in a few hours.  Closing this thread.  Please create a new issue if there are further problems.`
