### ISSUE TITLE
Expanded profile settings overlaps menu

### ISSUE THREAD

**Issue by comradekingu** [mendhak/gpslogger#951]
It is not that clear how to get back to the menu once profile settings are open.
Swiping away the menu and opening it again from the top displays the same (profile) settings.

**Comment by mendhak** [comment]
Is this better:

https://user-images.githubusercontent.com/746276/154587192-26017050-5dc5-4735-8f2e-ad19016d7e11.mp4

**Comment by comradekingu** [comment]
Better, yes.
Somewhat confused by clicking anything in the profile selector getting rid of it, but that is another issue.

**Comment by mendhak** [comment]
I was able to keep the drawer open when clicking something in profile selector, but sadly I could not find any method to keep the profile list itself open.  So now instead of the whole drawer closing right away, it will be like this:


![image](https://user-images.githubusercontent.com/746276/154748264-d354f1ae-5849-40f4-828a-d7ae01e31f0e.png)

**Comment by mendhak** [comment]
v121 is now in [F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and the [releases](https://github.com/mendhak/gpslogger/releases/tag/v121).
