### ISSUE TITLE
[FEATURE REQUEST] Log to custom URL -> Option to set an alternative/secondary server address!

### ISSUE THREAD

**Issue by pjakoby** [mendhak/gpslogger#964]
If the main server custom URL (e.g. myserver.com) is not reachable after x attempts, it would be great, if the app could try to connect to an alternative / secondary server address (e.g. mybackup.com).

I would really like this feature, because it would make the app super useful and even more reliable, if the main server is down for whatever reason.

**Comment by mendhak** [comment]
Hi there, sorry I've had a few requests to modify the Custom URL behavior, but I don't really want to make this application responsible for any 'custom' recovery/retry workflows, or to be treated differently from other logging types, because it ends up in a lot more maintenance overhead for me.  

However - I did create the Custom URL auto-send feature which is meant to be the fallback position; if the sending fails then the auto send can be used later, as a retry mechanism, and it will send the same requests to the server as before. As long as auto send for custom URL was enabled, or CSV logging was enabled.
