### ISSUE TITLE
TLS1.3 on Android<8.1

### ISSUE THREAD

**Issue by TilmanJimenez** [mendhak/gpslogger#971]
I know this issue has been opened before (albeit with older versions of TLS) but they have since been closed and I don't want to necrobump (#374 , #637)

It should be possible since browsers on the same phone(s) have no problem accessing servers with only TLS1.3. I know this might not be a priority and I myself will just solve it by allowing TLS 1.2+. Maybe it will solve itself again with the passage of time and people not using older phones :)

**Comment by mendhak** [comment]
According to the [documentation](https://developer.android.com/reference/javax/net/ssl/SSLContext), TLS 1.3 requires Android 10+ (API level 29).  For pre-Android-10 I see there's a library called [Conscrypt](https://stackoverflow.com/questions/55539513/how-to-enable-tlsv1-3-for-okhttp-3-12-x-on-android-8-9) which can help.  However I notice one awful thing right away - this library is huge (4 MB) and it brings the total APK size of GPSLogger to about 10 MB. 

I am trying out this library.  The only TLS 1.3 test site I can find is https://tls13.1d.pw let me know if you have a test site or how you're configuring TLS 1.3 only. 

Here is a test I did with that URL on Android 4.1 emulator. 

![image](https://user-images.githubusercontent.com/746276/174442653-19a81310-4d5f-4b6d-9911-f8a7c4971c9e.png)

**Comment by mendhak** [comment]
If you are able to test, an APK is here: https://github.com/mendhak/gpslogger/releases/tag/v123-rc1  

Note that this version is incompatible with the F-Droid version as they use different signatures; if you install this you'll lose all existing GPSLogger data.

**Comment by TilmanJimenez** [comment]
I'm currently on the road (and using this app! Still highly impressed with the low battery drainage) so I can't test.
I will be able to next week.
Server configuration for nginx should be
```
http{
    ...
    ssl_protocols          TLSv1.3;
    ...
}
```
I also understand if you don't want to basically double the size just to support old phones. In fact I would agree with that decision.

**Comment by mendhak** [comment]
Thanks for the config I will test this with a Docker image. 

So I've been mulling and searching over Conscrypt and started wondering, surely I cannot be the _first_ person to need to do this.  

I found a nice [blog post on F-droid](https://f-droid.org/2020/05/29/android-updates-and-tls-connections.html) as well as a [useful gist](https://gist.github.com/ByteHamster/f488f9993eeb6679c2b5f0180615d518) that could potentially provide a way to wrap Conscrypt in a separate app.  I would like to explore this option and tinker with it. It isn't the perfect option that's mentioned (installed by the user as a system app) but is probably the next best thing, and it can keep a huge bloat out of the app if it isn't needed. 

This would involve creating a second app, eg `gpslogger-conscrypt`, which bundles the Conscrypt library and also ensures that the Conscrypt security provider is being used. 
Since it is a separate app, the user would have to install it separately, perhaps some button on the settings screen can send the user there. 
If this app is installed, then gpslogger can detect it, and make a call to gpslogger-conscrypt.  
If it is not installed, gpslogger just uses the default of the OS.

**Comment by mendhak** [comment]
Implemented something...  I've re-uploaded the APK here: https://github.com/mendhak/gpslogger/releases/tag/v123-rc1 

On the OpenStreetMap and Cusotm URL screen you'll see an item at the bottom talking about Conscrypt. 

![image](https://user-images.githubusercontent.com/746276/174682933-d94f3fe2-fa4d-41e9-ae08-e93e5a14388f.png)

Press that, you'll get sent to a different Github Repo.  That will have an APK. If you install that APK, next time GPSLogger starts it will detect that Conscrypt Provider, and include it.  That should then help with OSM both the authorization as well as the upload job.  

This solves two problems - modern TLS for older devices, and it reduces bloat in the main application.  Only the users that need it can install this extra APK, that is, if they are having connectivity problems.  

Also let me know if the wording can be improved somehow.  It's difficult to explain TLS in a general way that most users can understand. 

No worries about the timing I'll just leave the APK there for testing.  I also need to do some testing of the other loggers/senders since they can benefit from modern TLS too.

**Comment by TilmanJimenez** [comment]
Maybe the wording could be something among the lines of:
Older Android phones might no longer be able to connect to services supporting exclusively the most modern protocols. If you're having connection problems, installing ...
If there could be a test button (checking if the site only supports TLS1.3) that might help (or an error in the log view?). Sadly I currently don't remember the error message that led me to discover this, that information might help describe how to figure out if an installation helps. I would provide that next week as well 👍
Thanks for your hard work!

**Comment by mendhak** [comment]
This stalled a bit because I was hoping that the F-Droid app for Conscrypt Provider would go through, which would make it easy to install, but that hasn't happened yet. So I'll just go ahead with the Github installation location.

Also I've moved the Conscrypt Provider item into General settings (not in the APK yet). The branch is merged but it'll be a while before I push to F-Droid.

**Comment by mendhak** [comment]
F-Droid [pull request has been merged](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11236).  I'm planning on waiting for this app to become available on F-Droid storefront, then I want to modify the code and just send people there if they're on the F-Droid GPSLogger, else to the Github link.

**Comment by mendhak** [comment]
OK it's on F-Droid now:  https://f-droid.org/en/packages/com.mendhak.gpslogger/  
Closing this issue
