### ISSUE TITLE
[FEATURE REQUEST] - Reimplement Google Drive uploading

### ISSUE THREAD

**Issue by KTKillo** [mendhak/gpslogger#972]
As previously, be able to upload files to Google Drive. Even Better if we can choose a 2nd or 3rd level of folder, and not only a folder in root.

(I've searched, and I think there is not requested yet)

**Comment by mendhak** [comment]
Yeah it'd be good if Google Drive could be brought back, that was my main upload target actually.  There's two parts to the task - authentication, and the actual uploading.  

### Authentication

Today I have done some research about various approaches for this.  I cannot use any closed source libraries, but sadly my options regarding a Google Sign In are quite limited.  There's a default assumption in all documentation, that everyone will be using their [closed source library to sign in](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignIn).  Anywhere I see `GoogleSignIn`, that's their proprietary library.  Also their Google Drive API [quickstart](https://developers.google.com/drive/api/quickstart/java) has no examples for Android which isn't helpful.  

There may be an alternative using **AppAuth Library**, and [there's a blog post about it here](https://medium.com/androiddevelopers/authenticating-on-android-with-the-appauth-library-7bea226555d5) which I will need to try. 

The other way to try would be using [**AccountManager**](https://developer.android.com/training/id-auth/authenticate). But if I remember correctly this requires the user to have an account on their phone signed in to Google.  Not all users may have a device account signed in, however if this is the simplest approach I will take it.  

There exists something called the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider) which makes it actually really easy to write a file directly to Google Drive just like a normal file.  I've had to rule this option out because of the way this application writes to files for efficiency, the SAF has no equivalents.  


### Upload

I think once the authentication is sorted, I should be able to reuse some of the [original upload code](https://github.com/mendhak/gpslogger/blob/12c01fb2f2df2dfc953dd22c57d13d7a9a564b1f/gpslogger/src/main/java/com/mendhak/gpslogger/senders/googledrive/GoogleDriveJob.java).  I'm glad I didn't use their original Drive library to do this, using their REST APIs instead.

**Comment by mendhak** [comment]
Authentication investigation. 

I tried the AccountManager way first.  I was able to go through the steps of, show the device accounts, then the user picks one, then in the callback I make a call to `getAuthToken` with the Google Drive scope.  At this point I get an error, `UNREGISTERED_ON_API_CONSOLE` and it turns out I need to register the application in Google Console, which is fine. I did that and got a token.  

One [detail](https://stackoverflow.com/a/41012703/974369) that caught me out is I'll need to register the SHA1 fingerprint of the signing key.  For F-Droid, it is [located here](https://f-droid.org/docs/Release_Channels_and_Signing_Keys/).  

    SHA1: 05:F2:E6:59:28:08:89:81:B3:17:FC:9A:6D:BF:E0:4B:0F:A1:3B:4E

I've preserved a copy of my code in [this commit](https://github.com/mendhak/gpslogger/commit/4e0909903ae10b3f20676f6af3b52cfa89faa2b1).  

First I launched the account chooser. 

```java
Intent intent = AccountManager.newChooseAccountIntent(null, null,
                new String[] { "com.google" }, true, null, null,
                null, null);
        PendingIntent piAcct = PendingIntent.getActivity(this,0, intent, 0);
        chooseAccount.launch(new IntentSenderRequest.Builder(piAcct).setFillInIntent(intent).build());
```

Then in the callback, 

```java
ActivityResultLauncher<IntentSenderRequest> chooseAccount =  registerForActivityResult(
            new ActivityResultContracts.StartIntentSenderForResult(),
            new ActivityResultCallback<ActivityResult>() {
        @Override
        public void onActivityResult(ActivityResult result) {
            LOG.debug("..........................................................");
            LOG.debug("..........................................................");
            LOG.debug("..........................................................");
            LOG.debug(String.valueOf(result.getData().getStringExtra(AccountManager.KEY_ACCOUNT_NAME)));
            LOG.debug(String.valueOf(result.getData().getStringExtra(AccountManager.KEY_ACCOUNT_TYPE)));
            AccountManager am = AccountManager.get(getApplicationContext());

            am.getAuthToken(am.getAccountsByType("com.google")[0], "oauth2:https://www.googleapis.com/auth/drive.file", new Bundle(),
                    (Activity)GpsMainActivity.this, new AccountManagerCallback<Bundle>() {
                        @Override
                        public void run(AccountManagerFuture<Bundle> accountManagerFuture) {
                            try {
                                LOG.debug(accountManagerFuture.getResult().getString(AccountManager.KEY_AUTHTOKEN));
                            } catch (Exception e) {
                                LOG.error(e.getMessage(), e);
                            }
                        }
                    }, new Handler(Looper.getMainLooper()));

        }
    });
```

Completely untested properly but I did get a token, so that's a start at least.  

This doesn't work on devices that don't have a signed in account.  I'll keep this as a second resort since it does require the device to have a signed in account and some people might not have that.

**Comment by mendhak** [comment]
Authentication investigation, with AppAuth library by OpenID. 

This was hard to understand/implement, but the [blog post](https://medium.com/androiddevelopers/authenticating-on-android-with-the-appauth-library-7bea226555d5) proved to be very useful.  I was able to authenticate with G Drive, limited permissions, and get an access token.  The difficult thing about this approach is just how dense and verbose it is. 

The good and bad news about this approach is it uses the browser, so you have to sign in to your Google Account in the browser.  It's a more 'universal' approach because it means the actual phone doesn't need a Google account to be signed in at the device level, only in the browser while the authorization happens.  It's less convenient for people who do have a Google account at the device level, and might have to sign in to their browser again (eg using Chrome on Android might mean, already signed in; Firefox on Android will mean sign in again)

Code is preserved in [this commit here](https://github.com/mendhak/gpslogger/commit/c3d5bb298c491a1854a5379230e701553b04fa49).  

Despite how much more work it is to implement, this way does look promising.  I would like to pursue with using AppAuth library, let's see how it goes.

**Comment by mendhak** [comment]
I've finally got a Google Drive implementation that seems to work well enough for me on a few emulators and devices, I've been running it for a few days. 

![image](https://user-images.githubusercontent.com/746276/170940318-e630dfce-6186-4ef8-8fd3-fc27f2652406.png)


@KTKillo or anyone following, if you are able to test, you can get an APK here: https://github.com/mendhak/gpslogger/releases/tag/v122-rc3 but note that this APK is incompatible with the F-Droid version, you will lose all previous GPSLogger data. 

I've added a textbox that lets the user specify the Google Drive path, but there is a restriction - the path or folders must have been created by this application.  To put it another way, it cannot use _existing_ paths in your Google Drive.  

Another thing to note about paths is it's going to be slower.  Because of some weird Google Drive design decisions, I have to check for each folder to exist and create it if it doesn't, and each step is 2 HTTP calls, so the longer the path, the slower the upload. 

You can also just specify a folder name, which is slightly faster.  

This is what the consent screen should look like.  I'd be interested to know if it looks different for anyone else. I've submitted the OAuth Consent Screen for verification to Google, but they've said it can take up to 6 week. :neutral_face: 
![image](https://user-images.githubusercontent.com/746276/170939467-d5ea75d2-3a86-4b05-bfb1-6b6c52ed541f.png)

**Comment by KTKillo** [comment]
Great news, @mendhak !

I will try this version in some phones and tablets this week.
I'll check also the consent screen and take some screenshot if its diferent.

**Comment by mendhak** [comment]
Apologies, I think the previous APK upload may have broken as I removed the OAuth Client ID.  

I've reuploaded the [APKs](https://github.com/mendhak/gpslogger/releases/tag/v122-rc3) with a different OAuth Client ID - it should match the original Play Store 'GPSLogger for Android' folder, in case anyone was using the original GPSLogger.  To preserve a bit of continuity.

**Comment by bschatzow** [comment]
I have never updated from the old to the new one on F Droid. Will this new release allow me to update directly to this version?

**Comment by mendhak** [comment]
If you install the APKs that are on the [Releases page](https://github.com/mendhak/gpslogger/releases), you should be able to continue with your existing settings, and you'll get the latest version.  For future updates you'll need to download APKs again from this releases page.

If you go with the version on [F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/), you'll get a warning saying that the app version you're about to install, is incompatible with the version you've already got installed.  If you proceed it will uninstall your existing version and you'll lose your settings, you'll have to re-enter whatever settings you had before.  But you'll also be on the latest version.  With F-Droid's app manager it should install updates for you automatically.

Both ways work, just pick whatever's convenient for you.

**Comment by KTKillo** [comment]
Tested in Redmi Note 9, a Samsung Galaxy S9+ and a Samsung Galaxy Tab Active2 and it works fine for me. 
Just to confirm:

Same consent screen as you shown (with a previous one to select the Google account):

If you write a existing folder, it creates again and you can see two folders with the sema name (in the Android client for GDrive; in a regular PC with the drive attached, you see the (1) at the end of the new folder.
Once the folder is created by GPSLogger in GDrive's root, you can move the folder (using the apropiate option in GDrive Android client) to another subfolder, and the upload of files is still working.

**Comment by mendhak** [comment]
Thanks for testing. I think I'm happy with where this feature is  now so I will merge the branch.  I'll tag it later and it should take about a week or so for F-Droid to be updated with a new version.

**Comment by bschatzow** [comment]
Just installed RC 3 and it updated with no issues on my pixel xl 4 with the latest Android version. Thanks again for this app! I use it for location with Home Assistant.

**Comment by mendhak** [comment]
At last [Version 122 is on F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and [the releases](https://github.com/mendhak/gpslogger/releases/tag/v122).  Thanks for the nudge @KTKillo it was fun and at the same time frustrating trying to get this working and I'm glad I got somewhere. 

Google APIs really, really want you using their libraries instead of their REST APIs.  This is evident in their 'meh' documentation regarding authentication.  The docs regarding actual Drive REST API is good, it's just the missing stuff around the authentication that really assumes you're using one of their proprietary libraries.

**Comment by KTKillo** [comment]
Great work, Thanks a lot!
:)
