### ISSUE TITLE
[Q] Is GpsLogger supposed to show on the lock screen?

### ISSUE THREAD

**Issue by PulsarFX** [mendhak/gpslogger#990]
I'm struggling to get GpsLogger to show a notification on the lock screen while it is running. 
I've turned every notification setting to 11 in the android settings, but it only shows a notification when the screen is unlocked. 

Now I wonder: is this intentional? I'd like to see if it is running jus by glancing at the lock screen.

**Comment by mendhak** [comment]
Yes it was intentional I see it being hidden on the lockscreen on these lines, but can't remember why!  

https://github.com/mendhak/gpslogger/blob/9b2dfc9b48b2b0bfa081ed27bb7eec7b7d59146c/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L528   
https://github.com/mendhak/gpslogger/blob/9b2dfc9b48b2b0bfa081ed27bb7eec7b7d59146c/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L540  

I think I was just trying to make the app unobtrusive and out of the way.  I suppose there is no harm if you as the device owner want it to be visible, isn't it? 

I could try adding an option to make this notification visible on the lock screen.  There is a [VISIBILITY_PUBLIC](https://developer.android.com/reference/android/app/Notification#VISIBILITY_PUBLIC) property... that should do it.

**Comment by PulsarFX** [comment]
Ah this makes things clear ;-)
I think having it in a public channel is not a problem anymore, nor would it brake anything. Users can change the lockscreen appearance from the android notification settings on android versions where channels are supported.

**Comment by mendhak** [comment]
Added option to show notification on lock screen. Default is to hide it though. 
![image](https://user-images.githubusercontent.com/746276/179398341-c3f91c52-8c82-4345-ab9a-aacc757e2852.png)

![image](https://user-images.githubusercontent.com/746276/179398255-ba4f7cb5-0217-4f09-a13a-c546539c6096.png)

**Comment by mendhak** [comment]
OK it's on F-Droid now:  https://f-droid.org/en/packages/com.mendhak.gpslogger/  
Closing this issue
